// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/filepermission"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// FilePermissionUpdate is the builder for updating FilePermission entities.
type FilePermissionUpdate struct {
	config
	hooks    []Hook
	mutation *FilePermissionMutation
}

// Where appends a list predicates to the FilePermissionUpdate builder.
func (fpu *FilePermissionUpdate) Where(ps ...predicate.FilePermission) *FilePermissionUpdate {
	fpu.mutation.Where(ps...)
	return fpu
}

// SetUpdatedAt sets the "updated_at" field.
func (fpu *FilePermissionUpdate) SetUpdatedAt(t time.Time) *FilePermissionUpdate {
	fpu.mutation.SetUpdatedAt(t)
	return fpu
}

// SetDeletedAt sets the "deleted_at" field.
func (fpu *FilePermissionUpdate) SetDeletedAt(t time.Time) *FilePermissionUpdate {
	fpu.mutation.SetDeletedAt(t)
	return fpu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fpu *FilePermissionUpdate) SetNillableDeletedAt(t *time.Time) *FilePermissionUpdate {
	if t != nil {
		fpu.SetDeletedAt(*t)
	}
	return fpu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fpu *FilePermissionUpdate) ClearDeletedAt() *FilePermissionUpdate {
	fpu.mutation.ClearDeletedAt()
	return fpu
}

// SetFileID sets the "file_id" field.
func (fpu *FilePermissionUpdate) SetFileID(i int) *FilePermissionUpdate {
	fpu.mutation.ResetFileID()
	fpu.mutation.SetFileID(i)
	return fpu
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (fpu *FilePermissionUpdate) SetNillableFileID(i *int) *FilePermissionUpdate {
	if i != nil {
		fpu.SetFileID(*i)
	}
	return fpu
}

// AddFileID adds i to the "file_id" field.
func (fpu *FilePermissionUpdate) AddFileID(i int) *FilePermissionUpdate {
	fpu.mutation.AddFileID(i)
	return fpu
}

// SetSubjectType sets the "subject_type" field.
func (fpu *FilePermissionUpdate) SetSubjectType(s string) *FilePermissionUpdate {
	fpu.mutation.SetSubjectType(s)
	return fpu
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (fpu *FilePermissionUpdate) SetNillableSubjectType(s *string) *FilePermissionUpdate {
	if s != nil {
		fpu.SetSubjectType(*s)
	}
	return fpu
}

// SetSubjectID sets the "subject_id" field.
func (fpu *FilePermissionUpdate) SetSubjectID(i int) *FilePermissionUpdate {
	fpu.mutation.ResetSubjectID()
	fpu.mutation.SetSubjectID(i)
	return fpu
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (fpu *FilePermissionUpdate) SetNillableSubjectID(i *int) *FilePermissionUpdate {
	if i != nil {
		fpu.SetSubjectID(*i)
	}
	return fpu
}

// AddSubjectID adds i to the "subject_id" field.
func (fpu *FilePermissionUpdate) AddSubjectID(i int) *FilePermissionUpdate {
	fpu.mutation.AddSubjectID(i)
	return fpu
}

// SetPermission sets the "permission" field.
func (fpu *FilePermissionUpdate) SetPermission(s string) *FilePermissionUpdate {
	fpu.mutation.SetPermission(s)
	return fpu
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (fpu *FilePermissionUpdate) SetNillablePermission(s *string) *FilePermissionUpdate {
	if s != nil {
		fpu.SetPermission(*s)
	}
	return fpu
}

// SetInherit sets the "inherit" field.
func (fpu *FilePermissionUpdate) SetInherit(b bool) *FilePermissionUpdate {
	fpu.mutation.SetInherit(b)
	return fpu
}

// SetNillableInherit sets the "inherit" field if the given value is not nil.
func (fpu *FilePermissionUpdate) SetNillableInherit(b *bool) *FilePermissionUpdate {
	if b != nil {
		fpu.SetInherit(*b)
	}
	return fpu
}

// SetCreatedBy sets the "created_by" field.
func (fpu *FilePermissionUpdate) SetCreatedBy(i int) *FilePermissionUpdate {
	fpu.mutation.ResetCreatedBy()
	fpu.mutation.SetCreatedBy(i)
	return fpu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (fpu *FilePermissionUpdate) SetNillableCreatedBy(i *int) *FilePermissionUpdate {
	if i != nil {
		fpu.SetCreatedBy(*i)
	}
	return fpu
}

// AddCreatedBy adds i to the "created_by" field.
func (fpu *FilePermissionUpdate) AddCreatedBy(i int) *FilePermissionUpdate {
	fpu.mutation.AddCreatedBy(i)
	return fpu
}

// Mutation returns the FilePermissionMutation object of the builder.
func (fpu *FilePermissionUpdate) Mutation() *FilePermissionMutation {
	return fpu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fpu *FilePermissionUpdate) Save(ctx context.Context) (int, error) {
	if err := fpu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, fpu.sqlSave, fpu.mutation, fpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fpu *FilePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := fpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fpu *FilePermissionUpdate) Exec(ctx context.Context) error {
	_, err := fpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fpu *FilePermissionUpdate) ExecX(ctx context.Context) {
	if err := fpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fpu *FilePermissionUpdate) defaults() error {
	if _, ok := fpu.mutation.UpdatedAt(); !ok {
		if filepermission.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized filepermission.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := filepermission.UpdateDefaultUpdatedAt()
		fpu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fpu *FilePermissionUpdate) check() error {
	if v, ok := fpu.mutation.SubjectType(); ok {
		if err := filepermission.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "FilePermission.subject_type": %w`, err)}
		}
	}
	if v, ok := fpu.mutation.Permission(); ok {
		if err := filepermission.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "FilePermission.permission": %w`, err)}
		}
	}
	return nil
}

func (fpu *FilePermissionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(filepermission.Table, filepermission.Columns, sqlgraph.NewFieldSpec(filepermission.FieldID, field.TypeInt))
	if ps := fpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fpu.mutation.UpdatedAt(); ok {
		_spec.SetField(filepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := fpu.mutation.DeletedAt(); ok {
		_spec.SetField(filepermission.FieldDeletedAt, field.TypeTime, value)
	}
	if fpu.mutation.DeletedAtCleared() {
		_spec.ClearField(filepermission.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := fpu.mutation.FileID(); ok {
		_spec.SetField(filepermission.FieldFileID, field.TypeInt, value)
	}
	if value, ok := fpu.mutation.AddedFileID(); ok {
		_spec.AddField(filepermission.FieldFileID, field.TypeInt, value)
	}
	if value, ok := fpu.mutation.SubjectType(); ok {
		_spec.SetField(filepermission.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := fpu.mutation.SubjectID(); ok {
		_spec.SetField(filepermission.FieldSubjectID, field.TypeInt, value)
	}
	if value, ok := fpu.mutation.AddedSubjectID(); ok {
		_spec.AddField(filepermission.FieldSubjectID, field.TypeInt, value)
	}
	if value, ok := fpu.mutation.Permission(); ok {
		_spec.SetField(filepermission.FieldPermission, field.TypeString, value)
	}
	if value, ok := fpu.mutation.Inherit(); ok {
		_spec.SetField(filepermission.FieldInherit, field.TypeBool, value)
	}
	if value, ok := fpu.mutation.CreatedBy(); ok {
		_spec.SetField(filepermission.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := fpu.mutation.AddedCreatedBy(); ok {
		_spec.AddField(filepermission.FieldCreatedBy, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fpu.mutation.done = true
	return n, nil
}

// FilePermissionUpdateOne is the builder for updating a single FilePermission entity.
type FilePermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FilePermissionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (fpuo *FilePermissionUpdateOne) SetUpdatedAt(t time.Time) *FilePermissionUpdateOne {
	fpuo.mutation.SetUpdatedAt(t)
	return fpuo
}

// SetDeletedAt sets the "deleted_at" field.
func (fpuo *FilePermissionUpdateOne) SetDeletedAt(t time.Time) *FilePermissionUpdateOne {
	fpuo.mutation.SetDeletedAt(t)
	return fpuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fpuo *FilePermissionUpdateOne) SetNillableDeletedAt(t *time.Time) *FilePermissionUpdateOne {
	if t != nil {
		fpuo.SetDeletedAt(*t)
	}
	return fpuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fpuo *FilePermissionUpdateOne) ClearDeletedAt() *FilePermissionUpdateOne {
	fpuo.mutation.ClearDeletedAt()
	return fpuo
}

// SetFileID sets the "file_id" field.
func (fpuo *FilePermissionUpdateOne) SetFileID(i int) *FilePermissionUpdateOne {
	fpuo.mutation.ResetFileID()
	fpuo.mutation.SetFileID(i)
	return fpuo
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (fpuo *FilePermissionUpdateOne) SetNillableFileID(i *int) *FilePermissionUpdateOne {
	if i != nil {
		fpuo.SetFileID(*i)
	}
	return fpuo
}

// AddFileID adds i to the "file_id" field.
func (fpuo *FilePermissionUpdateOne) AddFileID(i int) *FilePermissionUpdateOne {
	fpuo.mutation.AddFileID(i)
	return fpuo
}

// SetSubjectType sets the "subject_type" field.
func (fpuo *FilePermissionUpdateOne) SetSubjectType(s string) *FilePermissionUpdateOne {
	fpuo.mutation.SetSubjectType(s)
	return fpuo
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (fpuo *FilePermissionUpdateOne) SetNillableSubjectType(s *string) *FilePermissionUpdateOne {
	if s != nil {
		fpuo.SetSubjectType(*s)
	}
	return fpuo
}

// SetSubjectID sets the "subject_id" field.
func (fpuo *FilePermissionUpdateOne) SetSubjectID(i int) *FilePermissionUpdateOne {
	fpuo.mutation.ResetSubjectID()
	fpuo.mutation.SetSubjectID(i)
	return fpuo
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (fpuo *FilePermissionUpdateOne) SetNillableSubjectID(i *int) *FilePermissionUpdateOne {
	if i != nil {
		fpuo.SetSubjectID(*i)
	}
	return fpuo
}

// AddSubjectID adds i to the "subject_id" field.
func (fpuo *FilePermissionUpdateOne) AddSubjectID(i int) *FilePermissionUpdateOne {
	fpuo.mutation.AddSubjectID(i)
	return fpuo
}

// SetPermission sets the "permission" field.
func (fpuo *FilePermissionUpdateOne) SetPermission(s string) *FilePermissionUpdateOne {
	fpuo.mutation.SetPermission(s)
	return fpuo
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (fpuo *FilePermissionUpdateOne) SetNillablePermission(s *string) *FilePermissionUpdateOne {
	if s != nil {
		fpuo.SetPermission(*s)
	}
	return fpuo
}

// SetInherit sets the "inherit" field.
func (fpuo *FilePermissionUpdateOne) SetInherit(b bool) *FilePermissionUpdateOne {
	fpuo.mutation.SetInherit(b)
	return fpuo
}

// SetNillableInherit sets the "inherit" field if the given value is not nil.
func (fpuo *FilePermissionUpdateOne) SetNillableInherit(b *bool) *FilePermissionUpdateOne {
	if b != nil {
		fpuo.SetInherit(*b)
	}
	return fpuo
}

// SetCreatedBy sets the "created_by" field.
func (fpuo *FilePermissionUpdateOne) SetCreatedBy(i int) *FilePermissionUpdateOne {
	fpuo.mutation.ResetCreatedBy()
	fpuo.mutation.SetCreatedBy(i)
	return fpuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (fpuo *FilePermissionUpdateOne) SetNillableCreatedBy(i *int) *FilePermissionUpdateOne {
	if i != nil {
		fpuo.SetCreatedBy(*i)
	}
	return fpuo
}

// AddCreatedBy adds i to the "created_by" field.
func (fpuo *FilePermissionUpdateOne) AddCreatedBy(i int) *FilePermissionUpdateOne {
	fpuo.mutation.AddCreatedBy(i)
	return fpuo
}

// Mutation returns the FilePermissionMutation object of the builder.
func (fpuo *FilePermissionUpdateOne) Mutation() *FilePermissionMutation {
	return fpuo.mutation
}

// Where appends a list predicates to the FilePermissionUpdate builder.
func (fpuo *FilePermissionUpdateOne) Where(ps ...predicate.FilePermission) *FilePermissionUpdateOne {
	fpuo.mutation.Where(ps...)
	return fpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fpuo *FilePermissionUpdateOne) Select(field string, fields ...string) *FilePermissionUpdateOne {
	fpuo.fields = append([]string{field}, fields...)
	return fpuo
}

// Save executes the query and returns the updated FilePermission entity.
func (fpuo *FilePermissionUpdateOne) Save(ctx context.Context) (*FilePermission, error) {
	if err := fpuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, fpuo.sqlSave, fpuo.mutation, fpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fpuo *FilePermissionUpdateOne) SaveX(ctx context.Context) *FilePermission {
	node, err := fpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fpuo *FilePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := fpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fpuo *FilePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := fpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fpuo *FilePermissionUpdateOne) defaults() error {
	if _, ok := fpuo.mutation.UpdatedAt(); !ok {
		if filepermission.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized filepermission.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := filepermission.UpdateDefaultUpdatedAt()
		fpuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fpuo *FilePermissionUpdateOne) check() error {
	if v, ok := fpuo.mutation.SubjectType(); ok {
		if err := filepermission.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "FilePermission.subject_type": %w`, err)}
		}
	}
	if v, ok := fpuo.mutation.Permission(); ok {
		if err := filepermission.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "FilePermission.permission": %w`, err)}
		}
	}
	return nil
}

func (fpuo *FilePermissionUpdateOne) sqlSave(ctx context.Context) (_node *FilePermission, err error) {
	if err := fpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filepermission.Table, filepermission.Columns, sqlgraph.NewFieldSpec(filepermission.FieldID, field.TypeInt))
	id, ok := fpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FilePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filepermission.FieldID)
		for _, f := range fields {
			if !filepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != filepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fpuo.mutation.UpdatedAt(); ok {
		_spec.SetField(filepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := fpuo.mutation.DeletedAt(); ok {
		_spec.SetField(filepermission.FieldDeletedAt, field.TypeTime, value)
	}
	if fpuo.mutation.DeletedAtCleared() {
		_spec.ClearField(filepermission.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := fpuo.mutation.FileID(); ok {
		_spec.SetField(filepermission.FieldFileID, field.TypeInt, value)
	}
	if value, ok := fpuo.mutation.AddedFileID(); ok {
		_spec.AddField(filepermission.FieldFileID, field.TypeInt, value)
	}
	if value, ok := fpuo.mutation.SubjectType(); ok {
		_spec.SetField(filepermission.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := fpuo.mutation.SubjectID(); ok {
		_spec.SetField(filepermission.FieldSubjectID, field.TypeInt, value)
	}
	if value, ok := fpuo.mutation.AddedSubjectID(); ok {
		_spec.AddField(filepermission.FieldSubjectID, field.TypeInt, value)
	}
	if value, ok := fpuo.mutation.Permission(); ok {
		_spec.SetField(filepermission.FieldPermission, field.TypeString, value)
	}
	if value, ok := fpuo.mutation.Inherit(); ok {
		_spec.SetField(filepermission.FieldInherit, field.TypeBool, value)
	}
	if value, ok := fpuo.mutation.CreatedBy(); ok {
		_spec.SetField(filepermission.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := fpuo.mutation.AddedCreatedBy(); ok {
		_spec.AddField(filepermission.FieldCreatedBy, field.TypeInt, value)
	}
	_node = &FilePermission{config: fpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fpuo.mutation.done = true
	return _node, nil
}
