// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/filepermission"
)

// FilePermissionCreate is the builder for creating a FilePermission entity.
type FilePermissionCreate struct {
	config
	mutation *FilePermissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (fpc *FilePermissionCreate) SetCreatedAt(t time.Time) *FilePermissionCreate {
	fpc.mutation.SetCreatedAt(t)
	return fpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fpc *FilePermissionCreate) SetNillableCreatedAt(t *time.Time) *FilePermissionCreate {
	if t != nil {
		fpc.SetCreatedAt(*t)
	}
	return fpc
}

// SetUpdatedAt sets the "updated_at" field.
func (fpc *FilePermissionCreate) SetUpdatedAt(t time.Time) *FilePermissionCreate {
	fpc.mutation.SetUpdatedAt(t)
	return fpc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fpc *FilePermissionCreate) SetNillableUpdatedAt(t *time.Time) *FilePermissionCreate {
	if t != nil {
		fpc.SetUpdatedAt(*t)
	}
	return fpc
}

// SetDeletedAt sets the "deleted_at" field.
func (fpc *FilePermissionCreate) SetDeletedAt(t time.Time) *FilePermissionCreate {
	fpc.mutation.SetDeletedAt(t)
	return fpc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fpc *FilePermissionCreate) SetNillableDeletedAt(t *time.Time) *FilePermissionCreate {
	if t != nil {
		fpc.SetDeletedAt(*t)
	}
	return fpc
}

// SetFileID sets the "file_id" field.
func (fpc *FilePermissionCreate) SetFileID(i int) *FilePermissionCreate {
	fpc.mutation.SetFileID(i)
	return fpc
}

// SetSubjectType sets the "subject_type" field.
func (fpc *FilePermissionCreate) SetSubjectType(s string) *FilePermissionCreate {
	fpc.mutation.SetSubjectType(s)
	return fpc
}

// SetSubjectID sets the "subject_id" field.
func (fpc *FilePermissionCreate) SetSubjectID(i int) *FilePermissionCreate {
	fpc.mutation.SetSubjectID(i)
	return fpc
}

// SetPermission sets the "permission" field.
func (fpc *FilePermissionCreate) SetPermission(s string) *FilePermissionCreate {
	fpc.mutation.SetPermission(s)
	return fpc
}

// SetInherit sets the "inherit" field.
func (fpc *FilePermissionCreate) SetInherit(b bool) *FilePermissionCreate {
	fpc.mutation.SetInherit(b)
	return fpc
}

// SetNillableInherit sets the "inherit" field if the given value is not nil.
func (fpc *FilePermissionCreate) SetNillableInherit(b *bool) *FilePermissionCreate {
	if b != nil {
		fpc.SetInherit(*b)
	}
	return fpc
}

// SetCreatedBy sets the "created_by" field.
func (fpc *FilePermissionCreate) SetCreatedBy(i int) *FilePermissionCreate {
	fpc.mutation.SetCreatedBy(i)
	return fpc
}

// Mutation returns the FilePermissionMutation object of the builder.
func (fpc *FilePermissionCreate) Mutation() *FilePermissionMutation {
	return fpc.mutation
}

// Save creates the FilePermission in the database.
func (fpc *FilePermissionCreate) Save(ctx context.Context) (*FilePermission, error) {
	if err := fpc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, fpc.sqlSave, fpc.mutation, fpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fpc *FilePermissionCreate) SaveX(ctx context.Context) *FilePermission {
	v, err := fpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fpc *FilePermissionCreate) Exec(ctx context.Context) error {
	_, err := fpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fpc *FilePermissionCreate) ExecX(ctx context.Context) {
	if err := fpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fpc *FilePermissionCreate) defaults() error {
	if _, ok := fpc.mutation.CreatedAt(); !ok {
		if filepermission.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized filepermission.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := filepermission.DefaultCreatedAt()
		fpc.mutation.SetCreatedAt(v)
	}
	if _, ok := fpc.mutation.UpdatedAt(); !ok {
		if filepermission.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized filepermission.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := filepermission.DefaultUpdatedAt()
		fpc.mutation.SetUpdatedAt(v)
	}
	if _, ok := fpc.mutation.Inherit(); !ok {
		v := filepermission.DefaultInherit
		fpc.mutation.SetInherit(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fpc *FilePermissionCreate) check() error {
	if _, ok := fpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FilePermission.created_at"`)}
	}
	if _, ok := fpc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FilePermission.updated_at"`)}
	}
	if _, ok := fpc.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "FilePermission.file_id"`)}
	}
	if _, ok := fpc.mutation.SubjectType(); !ok {
		return &ValidationError{Name: "subject_type", err: errors.New(`ent: missing required field "FilePermission.subject_type"`)}
	}
	if v, ok := fpc.mutation.SubjectType(); ok {
		if err := filepermission.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "FilePermission.subject_type": %w`, err)}
		}
	}
	if _, ok := fpc.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "FilePermission.subject_id"`)}
	}
	if _, ok := fpc.mutation.Permission(); !ok {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required field "FilePermission.permission"`)}
	}
	if v, ok := fpc.mutation.Permission(); ok {
		if err := filepermission.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "FilePermission.permission": %w`, err)}
		}
	}
	if _, ok := fpc.mutation.Inherit(); !ok {
		return &ValidationError{Name: "inherit", err: errors.New(`ent: missing required field "FilePermission.inherit"`)}
	}
	if _, ok := fpc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "FilePermission.created_by"`)}
	}
	return nil
}

func (fpc *FilePermissionCreate) sqlSave(ctx context.Context) (*FilePermission, error) {
	if err := fpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fpc.mutation.id = &_node.ID
	fpc.mutation.done = true
	return _node, nil
}

func (fpc *FilePermissionCreate) createSpec() (*FilePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &FilePermission{config: fpc.config}
		_spec = sqlgraph.NewCreateSpec(filepermission.Table, sqlgraph.NewFieldSpec(filepermission.FieldID, field.TypeInt))
	)

	if id, ok := fpc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = fpc.conflict
	if value, ok := fpc.mutation.CreatedAt(); ok {
		_spec.SetField(filepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fpc.mutation.UpdatedAt(); ok {
		_spec.SetField(filepermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := fpc.mutation.DeletedAt(); ok {
		_spec.SetField(filepermission.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := fpc.mutation.FileID(); ok {
		_spec.SetField(filepermission.FieldFileID, field.TypeInt, value)
		_node.FileID = value
	}
	if value, ok := fpc.mutation.SubjectType(); ok {
		_spec.SetField(filepermission.FieldSubjectType, field.TypeString, value)
		_node.SubjectType = value
	}
	if value, ok := fpc.mutation.SubjectID(); ok {
		_spec.SetField(filepermission.FieldSubjectID, field.TypeInt, value)
		_node.SubjectID = value
	}
	if value, ok := fpc.mutation.Permission(); ok {
		_spec.SetField(filepermission.FieldPermission, field.TypeString, value)
		_node.Permission = value
	}
	if value, ok := fpc.mutation.Inherit(); ok {
		_spec.SetField(filepermission.FieldInherit, field.TypeBool, value)
		_node.Inherit = value
	}
	if value, ok := fpc.mutation.CreatedBy(); ok {
		_spec.SetField(filepermission.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FilePermission.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FilePermissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (fpc *FilePermissionCreate) OnConflict(opts ...sql.ConflictOption) *FilePermissionUpsertOne {
	fpc.conflict = opts
	return &FilePermissionUpsertOne{
		create: fpc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FilePermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (fpc *FilePermissionCreate) OnConflictColumns(columns ...string) *FilePermissionUpsertOne {
	fpc.conflict = append(fpc.conflict, sql.ConflictColumns(columns...))
	return &FilePermissionUpsertOne{
		create: fpc,
	}
}

type (
	// FilePermissionUpsertOne is the builder for "upsert"-ing
	//  one FilePermission node.
	FilePermissionUpsertOne struct {
		create *FilePermissionCreate
	}

	// FilePermissionUpsert is the "OnConflict" setter.
	FilePermissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FilePermissionUpsert) SetUpdatedAt(v time.Time) *FilePermissionUpsert {
	u.Set(filepermission.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdateUpdatedAt() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FilePermissionUpsert) SetDeletedAt(v time.Time) *FilePermissionUpsert {
	u.Set(filepermission.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdateDeletedAt() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FilePermissionUpsert) ClearDeletedAt() *FilePermissionUpsert {
	u.SetNull(filepermission.FieldDeletedAt)
	return u
}

// SetFileID sets the "file_id" field.
func (u *FilePermissionUpsert) SetFileID(v int) *FilePermissionUpsert {
	u.Set(filepermission.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdateFileID() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldFileID)
	return u
}

// AddFileID adds v to the "file_id" field.
func (u *FilePermissionUpsert) AddFileID(v int) *FilePermissionUpsert {
	u.Add(filepermission.FieldFileID, v)
	return u
}

// SetSubjectType sets the "subject_type" field.
func (u *FilePermissionUpsert) SetSubjectType(v string) *FilePermissionUpsert {
	u.Set(filepermission.FieldSubjectType, v)
	return u
}

// UpdateSubjectType sets the "subject_type" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdateSubjectType() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldSubjectType)
	return u
}

// SetSubjectID sets the "subject_id" field.
func (u *FilePermissionUpsert) SetSubjectID(v int) *FilePermissionUpsert {
	u.Set(filepermission.FieldSubjectID, v)
	return u
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdateSubjectID() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldSubjectID)
	return u
}

// AddSubjectID adds v to the "subject_id" field.
func (u *FilePermissionUpsert) AddSubjectID(v int) *FilePermissionUpsert {
	u.Add(filepermission.FieldSubjectID, v)
	return u
}

// SetPermission sets the "permission" field.
func (u *FilePermissionUpsert) SetPermission(v string) *FilePermissionUpsert {
	u.Set(filepermission.FieldPermission, v)
	return u
}

// UpdatePermission sets the "permission" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdatePermission() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldPermission)
	return u
}

// SetInherit sets the "inherit" field.
func (u *FilePermissionUpsert) SetInherit(v bool) *FilePermissionUpsert {
	u.Set(filepermission.FieldInherit, v)
	return u
}

// UpdateInherit sets the "inherit" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdateInherit() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldInherit)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *FilePermissionUpsert) SetCreatedBy(v int) *FilePermissionUpsert {
	u.Set(filepermission.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *FilePermissionUpsert) UpdateCreatedBy() *FilePermissionUpsert {
	u.SetExcluded(filepermission.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *FilePermissionUpsert) AddCreatedBy(v int) *FilePermissionUpsert {
	u.Add(filepermission.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FilePermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FilePermissionUpsertOne) UpdateNewValues() *FilePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(filepermission.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FilePermission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FilePermissionUpsertOne) Ignore() *FilePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FilePermissionUpsertOne) DoNothing() *FilePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FilePermissionCreate.OnConflict
// documentation for more info.
func (u *FilePermissionUpsertOne) Update(set func(*FilePermissionUpsert)) *FilePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FilePermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FilePermissionUpsertOne) SetUpdatedAt(v time.Time) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdateUpdatedAt() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FilePermissionUpsertOne) SetDeletedAt(v time.Time) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdateDeletedAt() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FilePermissionUpsertOne) ClearDeletedAt() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetFileID sets the "file_id" field.
func (u *FilePermissionUpsertOne) SetFileID(v int) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *FilePermissionUpsertOne) AddFileID(v int) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdateFileID() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateFileID()
	})
}

// SetSubjectType sets the "subject_type" field.
func (u *FilePermissionUpsertOne) SetSubjectType(v string) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetSubjectType(v)
	})
}

// UpdateSubjectType sets the "subject_type" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdateSubjectType() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateSubjectType()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *FilePermissionUpsertOne) SetSubjectID(v int) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetSubjectID(v)
	})
}

// AddSubjectID adds v to the "subject_id" field.
func (u *FilePermissionUpsertOne) AddSubjectID(v int) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.AddSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdateSubjectID() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateSubjectID()
	})
}

// SetPermission sets the "permission" field.
func (u *FilePermissionUpsertOne) SetPermission(v string) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetPermission(v)
	})
}

// UpdatePermission sets the "permission" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdatePermission() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdatePermission()
	})
}

// SetInherit sets the "inherit" field.
func (u *FilePermissionUpsertOne) SetInherit(v bool) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetInherit(v)
	})
}

// UpdateInherit sets the "inherit" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdateInherit() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateInherit()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *FilePermissionUpsertOne) SetCreatedBy(v int) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *FilePermissionUpsertOne) AddCreatedBy(v int) *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *FilePermissionUpsertOne) UpdateCreatedBy() *FilePermissionUpsertOne {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *FilePermissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FilePermissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FilePermissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FilePermissionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FilePermissionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *FilePermissionCreate) SetRawID(t int) *FilePermissionCreate {
	m.mutation.SetRawID(t)
	return m
}

// FilePermissionCreateBulk is the builder for creating many FilePermission entities in bulk.
type FilePermissionCreateBulk struct {
	config
	err      error
	builders []*FilePermissionCreate
	conflict []sql.ConflictOption
}

// Save creates the FilePermission entities in the database.
func (fpcb *FilePermissionCreateBulk) Save(ctx context.Context) ([]*FilePermission, error) {
	if fpcb.err != nil {
		return nil, fpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fpcb.builders))
	nodes := make([]*FilePermission, len(fpcb.builders))
	mutators := make([]Mutator, len(fpcb.builders))
	for i := range fpcb.builders {
		func(i int, root context.Context) {
			builder := fpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FilePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = fpcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fpcb *FilePermissionCreateBulk) SaveX(ctx context.Context) []*FilePermission {
	v, err := fpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fpcb *FilePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := fpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fpcb *FilePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := fpcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FilePermission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FilePermissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (fpcb *FilePermissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *FilePermissionUpsertBulk {
	fpcb.conflict = opts
	return &FilePermissionUpsertBulk{
		create: fpcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FilePermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (fpcb *FilePermissionCreateBulk) OnConflictColumns(columns ...string) *FilePermissionUpsertBulk {
	fpcb.conflict = append(fpcb.conflict, sql.ConflictColumns(columns...))
	return &FilePermissionUpsertBulk{
		create: fpcb,
	}
}

// FilePermissionUpsertBulk is the builder for "upsert"-ing
// a bulk of FilePermission nodes.
type FilePermissionUpsertBulk struct {
	create *FilePermissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FilePermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FilePermissionUpsertBulk) UpdateNewValues() *FilePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(filepermission.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FilePermission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FilePermissionUpsertBulk) Ignore() *FilePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FilePermissionUpsertBulk) DoNothing() *FilePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FilePermissionCreateBulk.OnConflict
// documentation for more info.
func (u *FilePermissionUpsertBulk) Update(set func(*FilePermissionUpsert)) *FilePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FilePermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FilePermissionUpsertBulk) SetUpdatedAt(v time.Time) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdateUpdatedAt() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FilePermissionUpsertBulk) SetDeletedAt(v time.Time) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdateDeletedAt() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FilePermissionUpsertBulk) ClearDeletedAt() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetFileID sets the "file_id" field.
func (u *FilePermissionUpsertBulk) SetFileID(v int) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *FilePermissionUpsertBulk) AddFileID(v int) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdateFileID() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateFileID()
	})
}

// SetSubjectType sets the "subject_type" field.
func (u *FilePermissionUpsertBulk) SetSubjectType(v string) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetSubjectType(v)
	})
}

// UpdateSubjectType sets the "subject_type" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdateSubjectType() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateSubjectType()
	})
}

// SetSubjectID sets the "subject_id" field.
func (u *FilePermissionUpsertBulk) SetSubjectID(v int) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetSubjectID(v)
	})
}

// AddSubjectID adds v to the "subject_id" field.
func (u *FilePermissionUpsertBulk) AddSubjectID(v int) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.AddSubjectID(v)
	})
}

// UpdateSubjectID sets the "subject_id" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdateSubjectID() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateSubjectID()
	})
}

// SetPermission sets the "permission" field.
func (u *FilePermissionUpsertBulk) SetPermission(v string) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetPermission(v)
	})
}

// UpdatePermission sets the "permission" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdatePermission() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdatePermission()
	})
}

// SetInherit sets the "inherit" field.
func (u *FilePermissionUpsertBulk) SetInherit(v bool) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetInherit(v)
	})
}

// UpdateInherit sets the "inherit" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdateInherit() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateInherit()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *FilePermissionUpsertBulk) SetCreatedBy(v int) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *FilePermissionUpsertBulk) AddCreatedBy(v int) *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *FilePermissionUpsertBulk) UpdateCreatedBy() *FilePermissionUpsertBulk {
	return u.Update(func(s *FilePermissionUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *FilePermissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FilePermissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FilePermissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FilePermissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
