// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/teampost"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtopic"
)

// TeamPostCreate is the builder for creating a TeamPost entity.
type TeamPostCreate struct {
	config
	mutation *TeamPostMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (tpc *TeamPostCreate) SetCreatedAt(t time.Time) *TeamPostCreate {
	tpc.mutation.SetCreatedAt(t)
	return tpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tpc *TeamPostCreate) SetNillableCreatedAt(t *time.Time) *TeamPostCreate {
	if t != nil {
		tpc.SetCreatedAt(*t)
	}
	return tpc
}

// SetUpdatedAt sets the "updated_at" field.
func (tpc *TeamPostCreate) SetUpdatedAt(t time.Time) *TeamPostCreate {
	tpc.mutation.SetUpdatedAt(t)
	return tpc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tpc *TeamPostCreate) SetNillableUpdatedAt(t *time.Time) *TeamPostCreate {
	if t != nil {
		tpc.SetUpdatedAt(*t)
	}
	return tpc
}

// SetDeletedAt sets the "deleted_at" field.
func (tpc *TeamPostCreate) SetDeletedAt(t time.Time) *TeamPostCreate {
	tpc.mutation.SetDeletedAt(t)
	return tpc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tpc *TeamPostCreate) SetNillableDeletedAt(t *time.Time) *TeamPostCreate {
	if t != nil {
		tpc.SetDeletedAt(*t)
	}
	return tpc
}

// SetTopicID sets the "topic_id" field.
func (tpc *TeamPostCreate) SetTopicID(i int) *TeamPostCreate {
	tpc.mutation.SetTopicID(i)
	return tpc
}

// SetUserID sets the "user_id" field.
func (tpc *TeamPostCreate) SetUserID(i int) *TeamPostCreate {
	tpc.mutation.SetUserID(i)
	return tpc
}

// SetContent sets the "content" field.
func (tpc *TeamPostCreate) SetContent(s string) *TeamPostCreate {
	tpc.mutation.SetContent(s)
	return tpc
}

// SetFloor sets the "floor" field.
func (tpc *TeamPostCreate) SetFloor(i int) *TeamPostCreate {
	tpc.mutation.SetFloor(i)
	return tpc
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (tpc *TeamPostCreate) SetNillableFloor(i *int) *TeamPostCreate {
	if i != nil {
		tpc.SetFloor(*i)
	}
	return tpc
}

// SetParentID sets the "parent_id" field.
func (tpc *TeamPostCreate) SetParentID(i int) *TeamPostCreate {
	tpc.mutation.SetParentID(i)
	return tpc
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (tpc *TeamPostCreate) SetNillableParentID(i *int) *TeamPostCreate {
	if i != nil {
		tpc.SetParentID(*i)
	}
	return tpc
}

// SetTopic sets the "topic" edge to the TeamTopic entity.
func (tpc *TeamPostCreate) SetTopic(t *TeamTopic) *TeamPostCreate {
	return tpc.SetTopicID(t.ID)
}

// Mutation returns the TeamPostMutation object of the builder.
func (tpc *TeamPostCreate) Mutation() *TeamPostMutation {
	return tpc.mutation
}

// Save creates the TeamPost in the database.
func (tpc *TeamPostCreate) Save(ctx context.Context) (*TeamPost, error) {
	if err := tpc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, tpc.sqlSave, tpc.mutation, tpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tpc *TeamPostCreate) SaveX(ctx context.Context) *TeamPost {
	v, err := tpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tpc *TeamPostCreate) Exec(ctx context.Context) error {
	_, err := tpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpc *TeamPostCreate) ExecX(ctx context.Context) {
	if err := tpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tpc *TeamPostCreate) defaults() error {
	if _, ok := tpc.mutation.CreatedAt(); !ok {
		if teampost.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized teampost.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := teampost.DefaultCreatedAt()
		tpc.mutation.SetCreatedAt(v)
	}
	if _, ok := tpc.mutation.UpdatedAt(); !ok {
		if teampost.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teampost.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teampost.DefaultUpdatedAt()
		tpc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tpc.mutation.Floor(); !ok {
		v := teampost.DefaultFloor
		tpc.mutation.SetFloor(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tpc *TeamPostCreate) check() error {
	if _, ok := tpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamPost.created_at"`)}
	}
	if _, ok := tpc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamPost.updated_at"`)}
	}
	if _, ok := tpc.mutation.TopicID(); !ok {
		return &ValidationError{Name: "topic_id", err: errors.New(`ent: missing required field "TeamPost.topic_id"`)}
	}
	if _, ok := tpc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TeamPost.user_id"`)}
	}
	if _, ok := tpc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "TeamPost.content"`)}
	}
	if _, ok := tpc.mutation.Floor(); !ok {
		return &ValidationError{Name: "floor", err: errors.New(`ent: missing required field "TeamPost.floor"`)}
	}
	if _, ok := tpc.mutation.TopicID(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required edge "TeamPost.topic"`)}
	}
	return nil
}

func (tpc *TeamPostCreate) sqlSave(ctx context.Context) (*TeamPost, error) {
	if err := tpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tpc.mutation.id = &_node.ID
	tpc.mutation.done = true
	return _node, nil
}

func (tpc *TeamPostCreate) createSpec() (*TeamPost, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamPost{config: tpc.config}
		_spec = sqlgraph.NewCreateSpec(teampost.Table, sqlgraph.NewFieldSpec(teampost.FieldID, field.TypeInt))
	)

	if id, ok := tpc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = tpc.conflict
	if value, ok := tpc.mutation.CreatedAt(); ok {
		_spec.SetField(teampost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tpc.mutation.UpdatedAt(); ok {
		_spec.SetField(teampost.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tpc.mutation.DeletedAt(); ok {
		_spec.SetField(teampost.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := tpc.mutation.UserID(); ok {
		_spec.SetField(teampost.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := tpc.mutation.Content(); ok {
		_spec.SetField(teampost.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := tpc.mutation.Floor(); ok {
		_spec.SetField(teampost.FieldFloor, field.TypeInt, value)
		_node.Floor = value
	}
	if value, ok := tpc.mutation.ParentID(); ok {
		_spec.SetField(teampost.FieldParentID, field.TypeInt, value)
		_node.ParentID = &value
	}
	if nodes := tpc.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teampost.TopicTable,
			Columns: []string{teampost.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtopic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TopicID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamPost.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamPostUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (tpc *TeamPostCreate) OnConflict(opts ...sql.ConflictOption) *TeamPostUpsertOne {
	tpc.conflict = opts
	return &TeamPostUpsertOne{
		create: tpc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamPost.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tpc *TeamPostCreate) OnConflictColumns(columns ...string) *TeamPostUpsertOne {
	tpc.conflict = append(tpc.conflict, sql.ConflictColumns(columns...))
	return &TeamPostUpsertOne{
		create: tpc,
	}
}

type (
	// TeamPostUpsertOne is the builder for "upsert"-ing
	//  one TeamPost node.
	TeamPostUpsertOne struct {
		create *TeamPostCreate
	}

	// TeamPostUpsert is the "OnConflict" setter.
	TeamPostUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamPostUpsert) SetUpdatedAt(v time.Time) *TeamPostUpsert {
	u.Set(teampost.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamPostUpsert) UpdateUpdatedAt() *TeamPostUpsert {
	u.SetExcluded(teampost.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamPostUpsert) SetDeletedAt(v time.Time) *TeamPostUpsert {
	u.Set(teampost.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamPostUpsert) UpdateDeletedAt() *TeamPostUpsert {
	u.SetExcluded(teampost.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamPostUpsert) ClearDeletedAt() *TeamPostUpsert {
	u.SetNull(teampost.FieldDeletedAt)
	return u
}

// SetTopicID sets the "topic_id" field.
func (u *TeamPostUpsert) SetTopicID(v int) *TeamPostUpsert {
	u.Set(teampost.FieldTopicID, v)
	return u
}

// UpdateTopicID sets the "topic_id" field to the value that was provided on create.
func (u *TeamPostUpsert) UpdateTopicID() *TeamPostUpsert {
	u.SetExcluded(teampost.FieldTopicID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TeamPostUpsert) SetUserID(v int) *TeamPostUpsert {
	u.Set(teampost.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamPostUpsert) UpdateUserID() *TeamPostUpsert {
	u.SetExcluded(teampost.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *TeamPostUpsert) AddUserID(v int) *TeamPostUpsert {
	u.Add(teampost.FieldUserID, v)
	return u
}

// SetContent sets the "content" field.
func (u *TeamPostUpsert) SetContent(v string) *TeamPostUpsert {
	u.Set(teampost.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TeamPostUpsert) UpdateContent() *TeamPostUpsert {
	u.SetExcluded(teampost.FieldContent)
	return u
}

// SetFloor sets the "floor" field.
func (u *TeamPostUpsert) SetFloor(v int) *TeamPostUpsert {
	u.Set(teampost.FieldFloor, v)
	return u
}

// UpdateFloor sets the "floor" field to the value that was provided on create.
func (u *TeamPostUpsert) UpdateFloor() *TeamPostUpsert {
	u.SetExcluded(teampost.FieldFloor)
	return u
}

// AddFloor adds v to the "floor" field.
func (u *TeamPostUpsert) AddFloor(v int) *TeamPostUpsert {
	u.Add(teampost.FieldFloor, v)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *TeamPostUpsert) SetParentID(v int) *TeamPostUpsert {
	u.Set(teampost.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *TeamPostUpsert) UpdateParentID() *TeamPostUpsert {
	u.SetExcluded(teampost.FieldParentID)
	return u
}

// AddParentID adds v to the "parent_id" field.
func (u *TeamPostUpsert) AddParentID(v int) *TeamPostUpsert {
	u.Add(teampost.FieldParentID, v)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *TeamPostUpsert) ClearParentID() *TeamPostUpsert {
	u.SetNull(teampost.FieldParentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamPost.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamPostUpsertOne) UpdateNewValues() *TeamPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teampost.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamPost.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamPostUpsertOne) Ignore() *TeamPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamPostUpsertOne) DoNothing() *TeamPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamPostCreate.OnConflict
// documentation for more info.
func (u *TeamPostUpsertOne) Update(set func(*TeamPostUpsert)) *TeamPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamPostUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamPostUpsertOne) SetUpdatedAt(v time.Time) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamPostUpsertOne) UpdateUpdatedAt() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamPostUpsertOne) SetDeletedAt(v time.Time) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamPostUpsertOne) UpdateDeletedAt() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamPostUpsertOne) ClearDeletedAt() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTopicID sets the "topic_id" field.
func (u *TeamPostUpsertOne) SetTopicID(v int) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetTopicID(v)
	})
}

// UpdateTopicID sets the "topic_id" field to the value that was provided on create.
func (u *TeamPostUpsertOne) UpdateTopicID() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateTopicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamPostUpsertOne) SetUserID(v int) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *TeamPostUpsertOne) AddUserID(v int) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamPostUpsertOne) UpdateUserID() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateUserID()
	})
}

// SetContent sets the "content" field.
func (u *TeamPostUpsertOne) SetContent(v string) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TeamPostUpsertOne) UpdateContent() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateContent()
	})
}

// SetFloor sets the "floor" field.
func (u *TeamPostUpsertOne) SetFloor(v int) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetFloor(v)
	})
}

// AddFloor adds v to the "floor" field.
func (u *TeamPostUpsertOne) AddFloor(v int) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.AddFloor(v)
	})
}

// UpdateFloor sets the "floor" field to the value that was provided on create.
func (u *TeamPostUpsertOne) UpdateFloor() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateFloor()
	})
}

// SetParentID sets the "parent_id" field.
func (u *TeamPostUpsertOne) SetParentID(v int) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *TeamPostUpsertOne) AddParentID(v int) *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *TeamPostUpsertOne) UpdateParentID() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *TeamPostUpsertOne) ClearParentID() *TeamPostUpsertOne {
	return u.Update(func(s *TeamPostUpsert) {
		s.ClearParentID()
	})
}

// Exec executes the query.
func (u *TeamPostUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamPostCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamPostUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamPostUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamPostUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *TeamPostCreate) SetRawID(t int) *TeamPostCreate {
	m.mutation.SetRawID(t)
	return m
}

// TeamPostCreateBulk is the builder for creating many TeamPost entities in bulk.
type TeamPostCreateBulk struct {
	config
	err      error
	builders []*TeamPostCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamPost entities in the database.
func (tpcb *TeamPostCreateBulk) Save(ctx context.Context) ([]*TeamPost, error) {
	if tpcb.err != nil {
		return nil, tpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tpcb.builders))
	nodes := make([]*TeamPost, len(tpcb.builders))
	mutators := make([]Mutator, len(tpcb.builders))
	for i := range tpcb.builders {
		func(i int, root context.Context) {
			builder := tpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamPostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tpcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tpcb *TeamPostCreateBulk) SaveX(ctx context.Context) []*TeamPost {
	v, err := tpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tpcb *TeamPostCreateBulk) Exec(ctx context.Context) error {
	_, err := tpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpcb *TeamPostCreateBulk) ExecX(ctx context.Context) {
	if err := tpcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamPost.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamPostUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (tpcb *TeamPostCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamPostUpsertBulk {
	tpcb.conflict = opts
	return &TeamPostUpsertBulk{
		create: tpcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamPost.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tpcb *TeamPostCreateBulk) OnConflictColumns(columns ...string) *TeamPostUpsertBulk {
	tpcb.conflict = append(tpcb.conflict, sql.ConflictColumns(columns...))
	return &TeamPostUpsertBulk{
		create: tpcb,
	}
}

// TeamPostUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamPost nodes.
type TeamPostUpsertBulk struct {
	create *TeamPostCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamPost.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamPostUpsertBulk) UpdateNewValues() *TeamPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teampost.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamPost.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamPostUpsertBulk) Ignore() *TeamPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamPostUpsertBulk) DoNothing() *TeamPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamPostCreateBulk.OnConflict
// documentation for more info.
func (u *TeamPostUpsertBulk) Update(set func(*TeamPostUpsert)) *TeamPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamPostUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamPostUpsertBulk) SetUpdatedAt(v time.Time) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamPostUpsertBulk) UpdateUpdatedAt() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamPostUpsertBulk) SetDeletedAt(v time.Time) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamPostUpsertBulk) UpdateDeletedAt() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamPostUpsertBulk) ClearDeletedAt() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTopicID sets the "topic_id" field.
func (u *TeamPostUpsertBulk) SetTopicID(v int) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetTopicID(v)
	})
}

// UpdateTopicID sets the "topic_id" field to the value that was provided on create.
func (u *TeamPostUpsertBulk) UpdateTopicID() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateTopicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamPostUpsertBulk) SetUserID(v int) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *TeamPostUpsertBulk) AddUserID(v int) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamPostUpsertBulk) UpdateUserID() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateUserID()
	})
}

// SetContent sets the "content" field.
func (u *TeamPostUpsertBulk) SetContent(v string) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TeamPostUpsertBulk) UpdateContent() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateContent()
	})
}

// SetFloor sets the "floor" field.
func (u *TeamPostUpsertBulk) SetFloor(v int) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetFloor(v)
	})
}

// AddFloor adds v to the "floor" field.
func (u *TeamPostUpsertBulk) AddFloor(v int) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.AddFloor(v)
	})
}

// UpdateFloor sets the "floor" field to the value that was provided on create.
func (u *TeamPostUpsertBulk) UpdateFloor() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateFloor()
	})
}

// SetParentID sets the "parent_id" field.
func (u *TeamPostUpsertBulk) SetParentID(v int) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *TeamPostUpsertBulk) AddParentID(v int) *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *TeamPostUpsertBulk) UpdateParentID() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *TeamPostUpsertBulk) ClearParentID() *TeamPostUpsertBulk {
	return u.Update(func(s *TeamPostUpsert) {
		s.ClearParentID()
	})
}

// Exec executes the query.
func (u *TeamPostUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamPostCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamPostCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamPostUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
