// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/teamactivity"
	"github.com/cloudreve/Cloudreve/v4/ent/teamdoc"
	"github.com/cloudreve/Cloudreve/v4/ent/teammember"
	"github.com/cloudreve/Cloudreve/v4/ent/teamproject"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtask"
)

// TeamProjectUpdate is the builder for updating TeamProject entities.
type TeamProjectUpdate struct {
	config
	hooks    []Hook
	mutation *TeamProjectMutation
}

// Where appends a list predicates to the TeamProjectUpdate builder.
func (tpu *TeamProjectUpdate) Where(ps ...predicate.TeamProject) *TeamProjectUpdate {
	tpu.mutation.Where(ps...)
	return tpu
}

// SetUpdatedAt sets the "updated_at" field.
func (tpu *TeamProjectUpdate) SetUpdatedAt(t time.Time) *TeamProjectUpdate {
	tpu.mutation.SetUpdatedAt(t)
	return tpu
}

// SetDeletedAt sets the "deleted_at" field.
func (tpu *TeamProjectUpdate) SetDeletedAt(t time.Time) *TeamProjectUpdate {
	tpu.mutation.SetDeletedAt(t)
	return tpu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tpu *TeamProjectUpdate) SetNillableDeletedAt(t *time.Time) *TeamProjectUpdate {
	if t != nil {
		tpu.SetDeletedAt(*t)
	}
	return tpu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tpu *TeamProjectUpdate) ClearDeletedAt() *TeamProjectUpdate {
	tpu.mutation.ClearDeletedAt()
	return tpu
}

// SetName sets the "name" field.
func (tpu *TeamProjectUpdate) SetName(s string) *TeamProjectUpdate {
	tpu.mutation.SetName(s)
	return tpu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tpu *TeamProjectUpdate) SetNillableName(s *string) *TeamProjectUpdate {
	if s != nil {
		tpu.SetName(*s)
	}
	return tpu
}

// SetDescription sets the "description" field.
func (tpu *TeamProjectUpdate) SetDescription(s string) *TeamProjectUpdate {
	tpu.mutation.SetDescription(s)
	return tpu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tpu *TeamProjectUpdate) SetNillableDescription(s *string) *TeamProjectUpdate {
	if s != nil {
		tpu.SetDescription(*s)
	}
	return tpu
}

// ClearDescription clears the value of the "description" field.
func (tpu *TeamProjectUpdate) ClearDescription() *TeamProjectUpdate {
	tpu.mutation.ClearDescription()
	return tpu
}

// SetOwnerID sets the "owner_id" field.
func (tpu *TeamProjectUpdate) SetOwnerID(i int) *TeamProjectUpdate {
	tpu.mutation.ResetOwnerID()
	tpu.mutation.SetOwnerID(i)
	return tpu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (tpu *TeamProjectUpdate) SetNillableOwnerID(i *int) *TeamProjectUpdate {
	if i != nil {
		tpu.SetOwnerID(*i)
	}
	return tpu
}

// AddOwnerID adds i to the "owner_id" field.
func (tpu *TeamProjectUpdate) AddOwnerID(i int) *TeamProjectUpdate {
	tpu.mutation.AddOwnerID(i)
	return tpu
}

// SetStatus sets the "status" field.
func (tpu *TeamProjectUpdate) SetStatus(s string) *TeamProjectUpdate {
	tpu.mutation.SetStatus(s)
	return tpu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tpu *TeamProjectUpdate) SetNillableStatus(s *string) *TeamProjectUpdate {
	if s != nil {
		tpu.SetStatus(*s)
	}
	return tpu
}

// SetSettings sets the "settings" field.
func (tpu *TeamProjectUpdate) SetSettings(m map[string]interface{}) *TeamProjectUpdate {
	tpu.mutation.SetSettings(m)
	return tpu
}

// ClearSettings clears the value of the "settings" field.
func (tpu *TeamProjectUpdate) ClearSettings() *TeamProjectUpdate {
	tpu.mutation.ClearSettings()
	return tpu
}

// AddTaskIDs adds the "tasks" edge to the TeamTask entity by IDs.
func (tpu *TeamProjectUpdate) AddTaskIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.AddTaskIDs(ids...)
	return tpu
}

// AddTasks adds the "tasks" edges to the TeamTask entity.
func (tpu *TeamProjectUpdate) AddTasks(t ...*TeamTask) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.AddTaskIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (tpu *TeamProjectUpdate) AddMemberIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.AddMemberIDs(ids...)
	return tpu
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (tpu *TeamProjectUpdate) AddMembers(t ...*TeamMember) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.AddMemberIDs(ids...)
}

// AddActivityIDs adds the "activities" edge to the TeamActivity entity by IDs.
func (tpu *TeamProjectUpdate) AddActivityIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.AddActivityIDs(ids...)
	return tpu
}

// AddActivities adds the "activities" edges to the TeamActivity entity.
func (tpu *TeamProjectUpdate) AddActivities(t ...*TeamActivity) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.AddActivityIDs(ids...)
}

// AddDocIDs adds the "docs" edge to the TeamDoc entity by IDs.
func (tpu *TeamProjectUpdate) AddDocIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.AddDocIDs(ids...)
	return tpu
}

// AddDocs adds the "docs" edges to the TeamDoc entity.
func (tpu *TeamProjectUpdate) AddDocs(t ...*TeamDoc) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.AddDocIDs(ids...)
}

// Mutation returns the TeamProjectMutation object of the builder.
func (tpu *TeamProjectUpdate) Mutation() *TeamProjectMutation {
	return tpu.mutation
}

// ClearTasks clears all "tasks" edges to the TeamTask entity.
func (tpu *TeamProjectUpdate) ClearTasks() *TeamProjectUpdate {
	tpu.mutation.ClearTasks()
	return tpu
}

// RemoveTaskIDs removes the "tasks" edge to TeamTask entities by IDs.
func (tpu *TeamProjectUpdate) RemoveTaskIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.RemoveTaskIDs(ids...)
	return tpu
}

// RemoveTasks removes "tasks" edges to TeamTask entities.
func (tpu *TeamProjectUpdate) RemoveTasks(t ...*TeamTask) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.RemoveTaskIDs(ids...)
}

// ClearMembers clears all "members" edges to the TeamMember entity.
func (tpu *TeamProjectUpdate) ClearMembers() *TeamProjectUpdate {
	tpu.mutation.ClearMembers()
	return tpu
}

// RemoveMemberIDs removes the "members" edge to TeamMember entities by IDs.
func (tpu *TeamProjectUpdate) RemoveMemberIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.RemoveMemberIDs(ids...)
	return tpu
}

// RemoveMembers removes "members" edges to TeamMember entities.
func (tpu *TeamProjectUpdate) RemoveMembers(t ...*TeamMember) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.RemoveMemberIDs(ids...)
}

// ClearActivities clears all "activities" edges to the TeamActivity entity.
func (tpu *TeamProjectUpdate) ClearActivities() *TeamProjectUpdate {
	tpu.mutation.ClearActivities()
	return tpu
}

// RemoveActivityIDs removes the "activities" edge to TeamActivity entities by IDs.
func (tpu *TeamProjectUpdate) RemoveActivityIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.RemoveActivityIDs(ids...)
	return tpu
}

// RemoveActivities removes "activities" edges to TeamActivity entities.
func (tpu *TeamProjectUpdate) RemoveActivities(t ...*TeamActivity) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.RemoveActivityIDs(ids...)
}

// ClearDocs clears all "docs" edges to the TeamDoc entity.
func (tpu *TeamProjectUpdate) ClearDocs() *TeamProjectUpdate {
	tpu.mutation.ClearDocs()
	return tpu
}

// RemoveDocIDs removes the "docs" edge to TeamDoc entities by IDs.
func (tpu *TeamProjectUpdate) RemoveDocIDs(ids ...int) *TeamProjectUpdate {
	tpu.mutation.RemoveDocIDs(ids...)
	return tpu
}

// RemoveDocs removes "docs" edges to TeamDoc entities.
func (tpu *TeamProjectUpdate) RemoveDocs(t ...*TeamDoc) *TeamProjectUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpu.RemoveDocIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tpu *TeamProjectUpdate) Save(ctx context.Context) (int, error) {
	if err := tpu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, tpu.sqlSave, tpu.mutation, tpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tpu *TeamProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := tpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tpu *TeamProjectUpdate) Exec(ctx context.Context) error {
	_, err := tpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpu *TeamProjectUpdate) ExecX(ctx context.Context) {
	if err := tpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tpu *TeamProjectUpdate) defaults() error {
	if _, ok := tpu.mutation.UpdatedAt(); !ok {
		if teamproject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamproject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamproject.UpdateDefaultUpdatedAt()
		tpu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tpu *TeamProjectUpdate) check() error {
	if v, ok := tpu.mutation.Name(); ok {
		if err := teamproject.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TeamProject.name": %w`, err)}
		}
	}
	return nil
}

func (tpu *TeamProjectUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamproject.Table, teamproject.Columns, sqlgraph.NewFieldSpec(teamproject.FieldID, field.TypeInt))
	if ps := tpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tpu.mutation.UpdatedAt(); ok {
		_spec.SetField(teamproject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tpu.mutation.DeletedAt(); ok {
		_spec.SetField(teamproject.FieldDeletedAt, field.TypeTime, value)
	}
	if tpu.mutation.DeletedAtCleared() {
		_spec.ClearField(teamproject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := tpu.mutation.Name(); ok {
		_spec.SetField(teamproject.FieldName, field.TypeString, value)
	}
	if value, ok := tpu.mutation.Description(); ok {
		_spec.SetField(teamproject.FieldDescription, field.TypeString, value)
	}
	if tpu.mutation.DescriptionCleared() {
		_spec.ClearField(teamproject.FieldDescription, field.TypeString)
	}
	if value, ok := tpu.mutation.OwnerID(); ok {
		_spec.SetField(teamproject.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := tpu.mutation.AddedOwnerID(); ok {
		_spec.AddField(teamproject.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := tpu.mutation.Status(); ok {
		_spec.SetField(teamproject.FieldStatus, field.TypeString, value)
	}
	if value, ok := tpu.mutation.Settings(); ok {
		_spec.SetField(teamproject.FieldSettings, field.TypeJSON, value)
	}
	if tpu.mutation.SettingsCleared() {
		_spec.ClearField(teamproject.FieldSettings, field.TypeJSON)
	}
	if tpu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.TasksTable,
			Columns: []string{teamproject.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.RemovedTasksIDs(); len(nodes) > 0 && !tpu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.TasksTable,
			Columns: []string{teamproject.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.TasksTable,
			Columns: []string{teamproject.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.MembersTable,
			Columns: []string{teamproject.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.RemovedMembersIDs(); len(nodes) > 0 && !tpu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.MembersTable,
			Columns: []string{teamproject.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.MembersTable,
			Columns: []string{teamproject.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpu.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.ActivitiesTable,
			Columns: []string{teamproject.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamactivity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.RemovedActivitiesIDs(); len(nodes) > 0 && !tpu.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.ActivitiesTable,
			Columns: []string{teamproject.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamactivity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.ActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.ActivitiesTable,
			Columns: []string{teamproject.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamactivity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpu.mutation.DocsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.DocsTable,
			Columns: []string{teamproject.DocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdoc.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.RemovedDocsIDs(); len(nodes) > 0 && !tpu.mutation.DocsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.DocsTable,
			Columns: []string{teamproject.DocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdoc.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.DocsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.DocsTable,
			Columns: []string{teamproject.DocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdoc.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamproject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tpu.mutation.done = true
	return n, nil
}

// TeamProjectUpdateOne is the builder for updating a single TeamProject entity.
type TeamProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamProjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (tpuo *TeamProjectUpdateOne) SetUpdatedAt(t time.Time) *TeamProjectUpdateOne {
	tpuo.mutation.SetUpdatedAt(t)
	return tpuo
}

// SetDeletedAt sets the "deleted_at" field.
func (tpuo *TeamProjectUpdateOne) SetDeletedAt(t time.Time) *TeamProjectUpdateOne {
	tpuo.mutation.SetDeletedAt(t)
	return tpuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tpuo *TeamProjectUpdateOne) SetNillableDeletedAt(t *time.Time) *TeamProjectUpdateOne {
	if t != nil {
		tpuo.SetDeletedAt(*t)
	}
	return tpuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tpuo *TeamProjectUpdateOne) ClearDeletedAt() *TeamProjectUpdateOne {
	tpuo.mutation.ClearDeletedAt()
	return tpuo
}

// SetName sets the "name" field.
func (tpuo *TeamProjectUpdateOne) SetName(s string) *TeamProjectUpdateOne {
	tpuo.mutation.SetName(s)
	return tpuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tpuo *TeamProjectUpdateOne) SetNillableName(s *string) *TeamProjectUpdateOne {
	if s != nil {
		tpuo.SetName(*s)
	}
	return tpuo
}

// SetDescription sets the "description" field.
func (tpuo *TeamProjectUpdateOne) SetDescription(s string) *TeamProjectUpdateOne {
	tpuo.mutation.SetDescription(s)
	return tpuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tpuo *TeamProjectUpdateOne) SetNillableDescription(s *string) *TeamProjectUpdateOne {
	if s != nil {
		tpuo.SetDescription(*s)
	}
	return tpuo
}

// ClearDescription clears the value of the "description" field.
func (tpuo *TeamProjectUpdateOne) ClearDescription() *TeamProjectUpdateOne {
	tpuo.mutation.ClearDescription()
	return tpuo
}

// SetOwnerID sets the "owner_id" field.
func (tpuo *TeamProjectUpdateOne) SetOwnerID(i int) *TeamProjectUpdateOne {
	tpuo.mutation.ResetOwnerID()
	tpuo.mutation.SetOwnerID(i)
	return tpuo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (tpuo *TeamProjectUpdateOne) SetNillableOwnerID(i *int) *TeamProjectUpdateOne {
	if i != nil {
		tpuo.SetOwnerID(*i)
	}
	return tpuo
}

// AddOwnerID adds i to the "owner_id" field.
func (tpuo *TeamProjectUpdateOne) AddOwnerID(i int) *TeamProjectUpdateOne {
	tpuo.mutation.AddOwnerID(i)
	return tpuo
}

// SetStatus sets the "status" field.
func (tpuo *TeamProjectUpdateOne) SetStatus(s string) *TeamProjectUpdateOne {
	tpuo.mutation.SetStatus(s)
	return tpuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tpuo *TeamProjectUpdateOne) SetNillableStatus(s *string) *TeamProjectUpdateOne {
	if s != nil {
		tpuo.SetStatus(*s)
	}
	return tpuo
}

// SetSettings sets the "settings" field.
func (tpuo *TeamProjectUpdateOne) SetSettings(m map[string]interface{}) *TeamProjectUpdateOne {
	tpuo.mutation.SetSettings(m)
	return tpuo
}

// ClearSettings clears the value of the "settings" field.
func (tpuo *TeamProjectUpdateOne) ClearSettings() *TeamProjectUpdateOne {
	tpuo.mutation.ClearSettings()
	return tpuo
}

// AddTaskIDs adds the "tasks" edge to the TeamTask entity by IDs.
func (tpuo *TeamProjectUpdateOne) AddTaskIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.AddTaskIDs(ids...)
	return tpuo
}

// AddTasks adds the "tasks" edges to the TeamTask entity.
func (tpuo *TeamProjectUpdateOne) AddTasks(t ...*TeamTask) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.AddTaskIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the TeamMember entity by IDs.
func (tpuo *TeamProjectUpdateOne) AddMemberIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.AddMemberIDs(ids...)
	return tpuo
}

// AddMembers adds the "members" edges to the TeamMember entity.
func (tpuo *TeamProjectUpdateOne) AddMembers(t ...*TeamMember) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.AddMemberIDs(ids...)
}

// AddActivityIDs adds the "activities" edge to the TeamActivity entity by IDs.
func (tpuo *TeamProjectUpdateOne) AddActivityIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.AddActivityIDs(ids...)
	return tpuo
}

// AddActivities adds the "activities" edges to the TeamActivity entity.
func (tpuo *TeamProjectUpdateOne) AddActivities(t ...*TeamActivity) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.AddActivityIDs(ids...)
}

// AddDocIDs adds the "docs" edge to the TeamDoc entity by IDs.
func (tpuo *TeamProjectUpdateOne) AddDocIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.AddDocIDs(ids...)
	return tpuo
}

// AddDocs adds the "docs" edges to the TeamDoc entity.
func (tpuo *TeamProjectUpdateOne) AddDocs(t ...*TeamDoc) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.AddDocIDs(ids...)
}

// Mutation returns the TeamProjectMutation object of the builder.
func (tpuo *TeamProjectUpdateOne) Mutation() *TeamProjectMutation {
	return tpuo.mutation
}

// ClearTasks clears all "tasks" edges to the TeamTask entity.
func (tpuo *TeamProjectUpdateOne) ClearTasks() *TeamProjectUpdateOne {
	tpuo.mutation.ClearTasks()
	return tpuo
}

// RemoveTaskIDs removes the "tasks" edge to TeamTask entities by IDs.
func (tpuo *TeamProjectUpdateOne) RemoveTaskIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.RemoveTaskIDs(ids...)
	return tpuo
}

// RemoveTasks removes "tasks" edges to TeamTask entities.
func (tpuo *TeamProjectUpdateOne) RemoveTasks(t ...*TeamTask) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.RemoveTaskIDs(ids...)
}

// ClearMembers clears all "members" edges to the TeamMember entity.
func (tpuo *TeamProjectUpdateOne) ClearMembers() *TeamProjectUpdateOne {
	tpuo.mutation.ClearMembers()
	return tpuo
}

// RemoveMemberIDs removes the "members" edge to TeamMember entities by IDs.
func (tpuo *TeamProjectUpdateOne) RemoveMemberIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.RemoveMemberIDs(ids...)
	return tpuo
}

// RemoveMembers removes "members" edges to TeamMember entities.
func (tpuo *TeamProjectUpdateOne) RemoveMembers(t ...*TeamMember) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.RemoveMemberIDs(ids...)
}

// ClearActivities clears all "activities" edges to the TeamActivity entity.
func (tpuo *TeamProjectUpdateOne) ClearActivities() *TeamProjectUpdateOne {
	tpuo.mutation.ClearActivities()
	return tpuo
}

// RemoveActivityIDs removes the "activities" edge to TeamActivity entities by IDs.
func (tpuo *TeamProjectUpdateOne) RemoveActivityIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.RemoveActivityIDs(ids...)
	return tpuo
}

// RemoveActivities removes "activities" edges to TeamActivity entities.
func (tpuo *TeamProjectUpdateOne) RemoveActivities(t ...*TeamActivity) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.RemoveActivityIDs(ids...)
}

// ClearDocs clears all "docs" edges to the TeamDoc entity.
func (tpuo *TeamProjectUpdateOne) ClearDocs() *TeamProjectUpdateOne {
	tpuo.mutation.ClearDocs()
	return tpuo
}

// RemoveDocIDs removes the "docs" edge to TeamDoc entities by IDs.
func (tpuo *TeamProjectUpdateOne) RemoveDocIDs(ids ...int) *TeamProjectUpdateOne {
	tpuo.mutation.RemoveDocIDs(ids...)
	return tpuo
}

// RemoveDocs removes "docs" edges to TeamDoc entities.
func (tpuo *TeamProjectUpdateOne) RemoveDocs(t ...*TeamDoc) *TeamProjectUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tpuo.RemoveDocIDs(ids...)
}

// Where appends a list predicates to the TeamProjectUpdate builder.
func (tpuo *TeamProjectUpdateOne) Where(ps ...predicate.TeamProject) *TeamProjectUpdateOne {
	tpuo.mutation.Where(ps...)
	return tpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tpuo *TeamProjectUpdateOne) Select(field string, fields ...string) *TeamProjectUpdateOne {
	tpuo.fields = append([]string{field}, fields...)
	return tpuo
}

// Save executes the query and returns the updated TeamProject entity.
func (tpuo *TeamProjectUpdateOne) Save(ctx context.Context) (*TeamProject, error) {
	if err := tpuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, tpuo.sqlSave, tpuo.mutation, tpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tpuo *TeamProjectUpdateOne) SaveX(ctx context.Context) *TeamProject {
	node, err := tpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tpuo *TeamProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := tpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpuo *TeamProjectUpdateOne) ExecX(ctx context.Context) {
	if err := tpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tpuo *TeamProjectUpdateOne) defaults() error {
	if _, ok := tpuo.mutation.UpdatedAt(); !ok {
		if teamproject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamproject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamproject.UpdateDefaultUpdatedAt()
		tpuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tpuo *TeamProjectUpdateOne) check() error {
	if v, ok := tpuo.mutation.Name(); ok {
		if err := teamproject.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TeamProject.name": %w`, err)}
		}
	}
	return nil
}

func (tpuo *TeamProjectUpdateOne) sqlSave(ctx context.Context) (_node *TeamProject, err error) {
	if err := tpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamproject.Table, teamproject.Columns, sqlgraph.NewFieldSpec(teamproject.FieldID, field.TypeInt))
	id, ok := tpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamProject.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamproject.FieldID)
		for _, f := range fields {
			if !teamproject.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamproject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tpuo.mutation.UpdatedAt(); ok {
		_spec.SetField(teamproject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tpuo.mutation.DeletedAt(); ok {
		_spec.SetField(teamproject.FieldDeletedAt, field.TypeTime, value)
	}
	if tpuo.mutation.DeletedAtCleared() {
		_spec.ClearField(teamproject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := tpuo.mutation.Name(); ok {
		_spec.SetField(teamproject.FieldName, field.TypeString, value)
	}
	if value, ok := tpuo.mutation.Description(); ok {
		_spec.SetField(teamproject.FieldDescription, field.TypeString, value)
	}
	if tpuo.mutation.DescriptionCleared() {
		_spec.ClearField(teamproject.FieldDescription, field.TypeString)
	}
	if value, ok := tpuo.mutation.OwnerID(); ok {
		_spec.SetField(teamproject.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := tpuo.mutation.AddedOwnerID(); ok {
		_spec.AddField(teamproject.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := tpuo.mutation.Status(); ok {
		_spec.SetField(teamproject.FieldStatus, field.TypeString, value)
	}
	if value, ok := tpuo.mutation.Settings(); ok {
		_spec.SetField(teamproject.FieldSettings, field.TypeJSON, value)
	}
	if tpuo.mutation.SettingsCleared() {
		_spec.ClearField(teamproject.FieldSettings, field.TypeJSON)
	}
	if tpuo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.TasksTable,
			Columns: []string{teamproject.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtask.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.RemovedTasksIDs(); len(nodes) > 0 && !tpuo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.TasksTable,
			Columns: []string{teamproject.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.TasksTable,
			Columns: []string{teamproject.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpuo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.MembersTable,
			Columns: []string{teamproject.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.RemovedMembersIDs(); len(nodes) > 0 && !tpuo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.MembersTable,
			Columns: []string{teamproject.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.MembersTable,
			Columns: []string{teamproject.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpuo.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.ActivitiesTable,
			Columns: []string{teamproject.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamactivity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.RemovedActivitiesIDs(); len(nodes) > 0 && !tpuo.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.ActivitiesTable,
			Columns: []string{teamproject.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamactivity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.ActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.ActivitiesTable,
			Columns: []string{teamproject.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamactivity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpuo.mutation.DocsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.DocsTable,
			Columns: []string{teamproject.DocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdoc.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.RemovedDocsIDs(); len(nodes) > 0 && !tpuo.mutation.DocsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.DocsTable,
			Columns: []string{teamproject.DocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdoc.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.DocsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teamproject.DocsTable,
			Columns: []string{teamproject.DocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamdoc.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamProject{config: tpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamproject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tpuo.mutation.done = true
	return _node, nil
}
