// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/teammember"
	"github.com/cloudreve/Cloudreve/v4/ent/teamproject"
)

// TeamMemberQuery is the builder for querying TeamMember entities.
type TeamMemberQuery struct {
	config
	ctx         *QueryContext
	order       []teammember.OrderOption
	inters      []Interceptor
	predicates  []predicate.TeamMember
	withProject *TeamProjectQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamMemberQuery builder.
func (tmq *TeamMemberQuery) Where(ps ...predicate.TeamMember) *TeamMemberQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit the number of records to be returned by this query.
func (tmq *TeamMemberQuery) Limit(limit int) *TeamMemberQuery {
	tmq.ctx.Limit = &limit
	return tmq
}

// Offset to start from.
func (tmq *TeamMemberQuery) Offset(offset int) *TeamMemberQuery {
	tmq.ctx.Offset = &offset
	return tmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tmq *TeamMemberQuery) Unique(unique bool) *TeamMemberQuery {
	tmq.ctx.Unique = &unique
	return tmq
}

// Order specifies how the records should be ordered.
func (tmq *TeamMemberQuery) Order(o ...teammember.OrderOption) *TeamMemberQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// QueryProject chains the current query on the "project" edge.
func (tmq *TeamMemberQuery) QueryProject() *TeamProjectQuery {
	query := (&TeamProjectClient{config: tmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teammember.Table, teammember.FieldID, selector),
			sqlgraph.To(teamproject.Table, teamproject.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, teammember.ProjectTable, teammember.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(tmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TeamMember entity from the query.
// Returns a *NotFoundError when no TeamMember was found.
func (tmq *TeamMemberQuery) First(ctx context.Context) (*TeamMember, error) {
	nodes, err := tmq.Limit(1).All(setContextOp(ctx, tmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teammember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TeamMemberQuery) FirstX(ctx context.Context) *TeamMember {
	node, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamMember ID from the query.
// Returns a *NotFoundError when no TeamMember ID was found.
func (tmq *TeamMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(1).IDs(setContextOp(ctx, tmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teammember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tmq *TeamMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TeamMember entity is found.
// Returns a *NotFoundError when no TeamMember entities are found.
func (tmq *TeamMemberQuery) Only(ctx context.Context) (*TeamMember, error) {
	nodes, err := tmq.Limit(2).All(setContextOp(ctx, tmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teammember.Label}
	default:
		return nil, &NotSingularError{teammember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TeamMemberQuery) OnlyX(ctx context.Context) *TeamMember {
	node, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamMember ID in the query.
// Returns a *NotSingularError when more than one TeamMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (tmq *TeamMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(2).IDs(setContextOp(ctx, tmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teammember.Label}
	default:
		err = &NotSingularError{teammember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TeamMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamMembers.
func (tmq *TeamMemberQuery) All(ctx context.Context) ([]*TeamMember, error) {
	ctx = setContextOp(ctx, tmq.ctx, "All")
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TeamMember, *TeamMemberQuery]()
	return withInterceptors[[]*TeamMember](ctx, tmq, qr, tmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TeamMemberQuery) AllX(ctx context.Context) []*TeamMember {
	nodes, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamMember IDs.
func (tmq *TeamMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tmq.ctx.Unique == nil && tmq.path != nil {
		tmq.Unique(true)
	}
	ctx = setContextOp(ctx, tmq.ctx, "IDs")
	if err = tmq.Select(teammember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TeamMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TeamMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tmq.ctx, "Count")
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tmq, querierCount[*TeamMemberQuery](), tmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TeamMemberQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TeamMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tmq.ctx, "Exist")
	switch _, err := tmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TeamMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TeamMemberQuery) Clone() *TeamMemberQuery {
	if tmq == nil {
		return nil
	}
	return &TeamMemberQuery{
		config:      tmq.config,
		ctx:         tmq.ctx.Clone(),
		order:       append([]teammember.OrderOption{}, tmq.order...),
		inters:      append([]Interceptor{}, tmq.inters...),
		predicates:  append([]predicate.TeamMember{}, tmq.predicates...),
		withProject: tmq.withProject.Clone(),
		// clone intermediate query.
		sql:  tmq.sql.Clone(),
		path: tmq.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (tmq *TeamMemberQuery) WithProject(opts ...func(*TeamProjectQuery)) *TeamMemberQuery {
	query := (&TeamProjectClient{config: tmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tmq.withProject = query
	return tmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamMember.Query().
//		GroupBy(teammember.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tmq *TeamMemberQuery) GroupBy(field string, fields ...string) *TeamMemberGroupBy {
	tmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeamMemberGroupBy{build: tmq}
	grbuild.flds = &tmq.ctx.Fields
	grbuild.label = teammember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.TeamMember.Query().
//		Select(teammember.FieldCreatedAt).
//		Scan(ctx, &v)
func (tmq *TeamMemberQuery) Select(fields ...string) *TeamMemberSelect {
	tmq.ctx.Fields = append(tmq.ctx.Fields, fields...)
	sbuild := &TeamMemberSelect{TeamMemberQuery: tmq}
	sbuild.label = teammember.Label
	sbuild.flds, sbuild.scan = &tmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeamMemberSelect configured with the given aggregations.
func (tmq *TeamMemberQuery) Aggregate(fns ...AggregateFunc) *TeamMemberSelect {
	return tmq.Select().Aggregate(fns...)
}

func (tmq *TeamMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tmq); err != nil {
				return err
			}
		}
	}
	for _, f := range tmq.ctx.Fields {
		if !teammember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TeamMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TeamMember, error) {
	var (
		nodes       = []*TeamMember{}
		_spec       = tmq.querySpec()
		loadedTypes = [1]bool{
			tmq.withProject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TeamMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TeamMember{config: tmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tmq.withProject; query != nil {
		if err := tmq.loadProject(ctx, query, nodes, nil,
			func(n *TeamMember, e *TeamProject) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tmq *TeamMemberQuery) loadProject(ctx context.Context, query *TeamProjectQuery, nodes []*TeamMember, init func(*TeamMember), assign func(*TeamMember, *TeamProject)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TeamMember)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(teamproject.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tmq *TeamMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	_spec.Node.Columns = tmq.ctx.Fields
	if len(tmq.ctx.Fields) > 0 {
		_spec.Unique = tmq.ctx.Unique != nil && *tmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TeamMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teammember.Table, teammember.Columns, sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt))
	_spec.From = tmq.sql
	if unique := tmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tmq.path != nil {
		_spec.Unique = true
	}
	if fields := tmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teammember.FieldID)
		for i := range fields {
			if fields[i] != teammember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tmq.withProject != nil {
			_spec.Node.AddColumnOnce(teammember.FieldProjectID)
		}
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TeamMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(teammember.Table)
	columns := tmq.ctx.Fields
	if len(columns) == 0 {
		columns = teammember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tmq.ctx.Unique != nil && *tmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TeamMemberGroupBy is the group-by builder for TeamMember entities.
type TeamMemberGroupBy struct {
	selector
	build *TeamMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TeamMemberGroupBy) Aggregate(fns ...AggregateFunc) *TeamMemberGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the selector query and scans the result into the given value.
func (tmgb *TeamMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tmgb.build.ctx, "GroupBy")
	if err := tmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamMemberQuery, *TeamMemberGroupBy](ctx, tmgb.build, tmgb, tmgb.build.inters, v)
}

func (tmgb *TeamMemberGroupBy) sqlScan(ctx context.Context, root *TeamMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tmgb.fns))
	for _, fn := range tmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tmgb.flds)+len(tmgb.fns))
		for _, f := range *tmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeamMemberSelect is the builder for selecting fields of TeamMember entities.
type TeamMemberSelect struct {
	*TeamMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tms *TeamMemberSelect) Aggregate(fns ...AggregateFunc) *TeamMemberSelect {
	tms.fns = append(tms.fns, fns...)
	return tms
}

// Scan applies the selector query and scans the result into the given value.
func (tms *TeamMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tms.ctx, "Select")
	if err := tms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamMemberQuery, *TeamMemberSelect](ctx, tms.TeamMemberQuery, tms, tms.inters, v)
}

func (tms *TeamMemberSelect) sqlScan(ctx context.Context, root *TeamMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tms.fns))
	for _, fn := range tms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
