// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/teamnotification"
)

// TeamNotificationUpdate is the builder for updating TeamNotification entities.
type TeamNotificationUpdate struct {
	config
	hooks    []Hook
	mutation *TeamNotificationMutation
}

// Where appends a list predicates to the TeamNotificationUpdate builder.
func (tnu *TeamNotificationUpdate) Where(ps ...predicate.TeamNotification) *TeamNotificationUpdate {
	tnu.mutation.Where(ps...)
	return tnu
}

// SetUpdatedAt sets the "updated_at" field.
func (tnu *TeamNotificationUpdate) SetUpdatedAt(t time.Time) *TeamNotificationUpdate {
	tnu.mutation.SetUpdatedAt(t)
	return tnu
}

// SetDeletedAt sets the "deleted_at" field.
func (tnu *TeamNotificationUpdate) SetDeletedAt(t time.Time) *TeamNotificationUpdate {
	tnu.mutation.SetDeletedAt(t)
	return tnu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableDeletedAt(t *time.Time) *TeamNotificationUpdate {
	if t != nil {
		tnu.SetDeletedAt(*t)
	}
	return tnu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tnu *TeamNotificationUpdate) ClearDeletedAt() *TeamNotificationUpdate {
	tnu.mutation.ClearDeletedAt()
	return tnu
}

// SetUserID sets the "user_id" field.
func (tnu *TeamNotificationUpdate) SetUserID(i int) *TeamNotificationUpdate {
	tnu.mutation.ResetUserID()
	tnu.mutation.SetUserID(i)
	return tnu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableUserID(i *int) *TeamNotificationUpdate {
	if i != nil {
		tnu.SetUserID(*i)
	}
	return tnu
}

// AddUserID adds i to the "user_id" field.
func (tnu *TeamNotificationUpdate) AddUserID(i int) *TeamNotificationUpdate {
	tnu.mutation.AddUserID(i)
	return tnu
}

// SetActorID sets the "actor_id" field.
func (tnu *TeamNotificationUpdate) SetActorID(i int) *TeamNotificationUpdate {
	tnu.mutation.ResetActorID()
	tnu.mutation.SetActorID(i)
	return tnu
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableActorID(i *int) *TeamNotificationUpdate {
	if i != nil {
		tnu.SetActorID(*i)
	}
	return tnu
}

// AddActorID adds i to the "actor_id" field.
func (tnu *TeamNotificationUpdate) AddActorID(i int) *TeamNotificationUpdate {
	tnu.mutation.AddActorID(i)
	return tnu
}

// ClearActorID clears the value of the "actor_id" field.
func (tnu *TeamNotificationUpdate) ClearActorID() *TeamNotificationUpdate {
	tnu.mutation.ClearActorID()
	return tnu
}

// SetType sets the "type" field.
func (tnu *TeamNotificationUpdate) SetType(s string) *TeamNotificationUpdate {
	tnu.mutation.SetType(s)
	return tnu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableType(s *string) *TeamNotificationUpdate {
	if s != nil {
		tnu.SetType(*s)
	}
	return tnu
}

// SetProjectID sets the "project_id" field.
func (tnu *TeamNotificationUpdate) SetProjectID(i int) *TeamNotificationUpdate {
	tnu.mutation.ResetProjectID()
	tnu.mutation.SetProjectID(i)
	return tnu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableProjectID(i *int) *TeamNotificationUpdate {
	if i != nil {
		tnu.SetProjectID(*i)
	}
	return tnu
}

// AddProjectID adds i to the "project_id" field.
func (tnu *TeamNotificationUpdate) AddProjectID(i int) *TeamNotificationUpdate {
	tnu.mutation.AddProjectID(i)
	return tnu
}

// ClearProjectID clears the value of the "project_id" field.
func (tnu *TeamNotificationUpdate) ClearProjectID() *TeamNotificationUpdate {
	tnu.mutation.ClearProjectID()
	return tnu
}

// SetTaskID sets the "task_id" field.
func (tnu *TeamNotificationUpdate) SetTaskID(i int) *TeamNotificationUpdate {
	tnu.mutation.ResetTaskID()
	tnu.mutation.SetTaskID(i)
	return tnu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableTaskID(i *int) *TeamNotificationUpdate {
	if i != nil {
		tnu.SetTaskID(*i)
	}
	return tnu
}

// AddTaskID adds i to the "task_id" field.
func (tnu *TeamNotificationUpdate) AddTaskID(i int) *TeamNotificationUpdate {
	tnu.mutation.AddTaskID(i)
	return tnu
}

// ClearTaskID clears the value of the "task_id" field.
func (tnu *TeamNotificationUpdate) ClearTaskID() *TeamNotificationUpdate {
	tnu.mutation.ClearTaskID()
	return tnu
}

// SetDocID sets the "doc_id" field.
func (tnu *TeamNotificationUpdate) SetDocID(i int) *TeamNotificationUpdate {
	tnu.mutation.ResetDocID()
	tnu.mutation.SetDocID(i)
	return tnu
}

// SetNillableDocID sets the "doc_id" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableDocID(i *int) *TeamNotificationUpdate {
	if i != nil {
		tnu.SetDocID(*i)
	}
	return tnu
}

// AddDocID adds i to the "doc_id" field.
func (tnu *TeamNotificationUpdate) AddDocID(i int) *TeamNotificationUpdate {
	tnu.mutation.AddDocID(i)
	return tnu
}

// ClearDocID clears the value of the "doc_id" field.
func (tnu *TeamNotificationUpdate) ClearDocID() *TeamNotificationUpdate {
	tnu.mutation.ClearDocID()
	return tnu
}

// SetTopicID sets the "topic_id" field.
func (tnu *TeamNotificationUpdate) SetTopicID(i int) *TeamNotificationUpdate {
	tnu.mutation.ResetTopicID()
	tnu.mutation.SetTopicID(i)
	return tnu
}

// SetNillableTopicID sets the "topic_id" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableTopicID(i *int) *TeamNotificationUpdate {
	if i != nil {
		tnu.SetTopicID(*i)
	}
	return tnu
}

// AddTopicID adds i to the "topic_id" field.
func (tnu *TeamNotificationUpdate) AddTopicID(i int) *TeamNotificationUpdate {
	tnu.mutation.AddTopicID(i)
	return tnu
}

// ClearTopicID clears the value of the "topic_id" field.
func (tnu *TeamNotificationUpdate) ClearTopicID() *TeamNotificationUpdate {
	tnu.mutation.ClearTopicID()
	return tnu
}

// SetTitle sets the "title" field.
func (tnu *TeamNotificationUpdate) SetTitle(s string) *TeamNotificationUpdate {
	tnu.mutation.SetTitle(s)
	return tnu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableTitle(s *string) *TeamNotificationUpdate {
	if s != nil {
		tnu.SetTitle(*s)
	}
	return tnu
}

// SetBody sets the "body" field.
func (tnu *TeamNotificationUpdate) SetBody(s string) *TeamNotificationUpdate {
	tnu.mutation.SetBody(s)
	return tnu
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableBody(s *string) *TeamNotificationUpdate {
	if s != nil {
		tnu.SetBody(*s)
	}
	return tnu
}

// ClearBody clears the value of the "body" field.
func (tnu *TeamNotificationUpdate) ClearBody() *TeamNotificationUpdate {
	tnu.mutation.ClearBody()
	return tnu
}

// SetIsRead sets the "is_read" field.
func (tnu *TeamNotificationUpdate) SetIsRead(b bool) *TeamNotificationUpdate {
	tnu.mutation.SetIsRead(b)
	return tnu
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (tnu *TeamNotificationUpdate) SetNillableIsRead(b *bool) *TeamNotificationUpdate {
	if b != nil {
		tnu.SetIsRead(*b)
	}
	return tnu
}

// Mutation returns the TeamNotificationMutation object of the builder.
func (tnu *TeamNotificationUpdate) Mutation() *TeamNotificationMutation {
	return tnu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tnu *TeamNotificationUpdate) Save(ctx context.Context) (int, error) {
	if err := tnu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, tnu.sqlSave, tnu.mutation, tnu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tnu *TeamNotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := tnu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tnu *TeamNotificationUpdate) Exec(ctx context.Context) error {
	_, err := tnu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tnu *TeamNotificationUpdate) ExecX(ctx context.Context) {
	if err := tnu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tnu *TeamNotificationUpdate) defaults() error {
	if _, ok := tnu.mutation.UpdatedAt(); !ok {
		if teamnotification.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamnotification.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamnotification.UpdateDefaultUpdatedAt()
		tnu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tnu *TeamNotificationUpdate) check() error {
	if v, ok := tnu.mutation.GetType(); ok {
		if err := teamnotification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TeamNotification.type": %w`, err)}
		}
	}
	if v, ok := tnu.mutation.Title(); ok {
		if err := teamnotification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TeamNotification.title": %w`, err)}
		}
	}
	return nil
}

func (tnu *TeamNotificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tnu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamnotification.Table, teamnotification.Columns, sqlgraph.NewFieldSpec(teamnotification.FieldID, field.TypeInt))
	if ps := tnu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tnu.mutation.UpdatedAt(); ok {
		_spec.SetField(teamnotification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tnu.mutation.DeletedAt(); ok {
		_spec.SetField(teamnotification.FieldDeletedAt, field.TypeTime, value)
	}
	if tnu.mutation.DeletedAtCleared() {
		_spec.ClearField(teamnotification.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := tnu.mutation.UserID(); ok {
		_spec.SetField(teamnotification.FieldUserID, field.TypeInt, value)
	}
	if value, ok := tnu.mutation.AddedUserID(); ok {
		_spec.AddField(teamnotification.FieldUserID, field.TypeInt, value)
	}
	if value, ok := tnu.mutation.ActorID(); ok {
		_spec.SetField(teamnotification.FieldActorID, field.TypeInt, value)
	}
	if value, ok := tnu.mutation.AddedActorID(); ok {
		_spec.AddField(teamnotification.FieldActorID, field.TypeInt, value)
	}
	if tnu.mutation.ActorIDCleared() {
		_spec.ClearField(teamnotification.FieldActorID, field.TypeInt)
	}
	if value, ok := tnu.mutation.GetType(); ok {
		_spec.SetField(teamnotification.FieldType, field.TypeString, value)
	}
	if value, ok := tnu.mutation.ProjectID(); ok {
		_spec.SetField(teamnotification.FieldProjectID, field.TypeInt, value)
	}
	if value, ok := tnu.mutation.AddedProjectID(); ok {
		_spec.AddField(teamnotification.FieldProjectID, field.TypeInt, value)
	}
	if tnu.mutation.ProjectIDCleared() {
		_spec.ClearField(teamnotification.FieldProjectID, field.TypeInt)
	}
	if value, ok := tnu.mutation.TaskID(); ok {
		_spec.SetField(teamnotification.FieldTaskID, field.TypeInt, value)
	}
	if value, ok := tnu.mutation.AddedTaskID(); ok {
		_spec.AddField(teamnotification.FieldTaskID, field.TypeInt, value)
	}
	if tnu.mutation.TaskIDCleared() {
		_spec.ClearField(teamnotification.FieldTaskID, field.TypeInt)
	}
	if value, ok := tnu.mutation.DocID(); ok {
		_spec.SetField(teamnotification.FieldDocID, field.TypeInt, value)
	}
	if value, ok := tnu.mutation.AddedDocID(); ok {
		_spec.AddField(teamnotification.FieldDocID, field.TypeInt, value)
	}
	if tnu.mutation.DocIDCleared() {
		_spec.ClearField(teamnotification.FieldDocID, field.TypeInt)
	}
	if value, ok := tnu.mutation.TopicID(); ok {
		_spec.SetField(teamnotification.FieldTopicID, field.TypeInt, value)
	}
	if value, ok := tnu.mutation.AddedTopicID(); ok {
		_spec.AddField(teamnotification.FieldTopicID, field.TypeInt, value)
	}
	if tnu.mutation.TopicIDCleared() {
		_spec.ClearField(teamnotification.FieldTopicID, field.TypeInt)
	}
	if value, ok := tnu.mutation.Title(); ok {
		_spec.SetField(teamnotification.FieldTitle, field.TypeString, value)
	}
	if value, ok := tnu.mutation.Body(); ok {
		_spec.SetField(teamnotification.FieldBody, field.TypeString, value)
	}
	if tnu.mutation.BodyCleared() {
		_spec.ClearField(teamnotification.FieldBody, field.TypeString)
	}
	if value, ok := tnu.mutation.IsRead(); ok {
		_spec.SetField(teamnotification.FieldIsRead, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tnu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tnu.mutation.done = true
	return n, nil
}

// TeamNotificationUpdateOne is the builder for updating a single TeamNotification entity.
type TeamNotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamNotificationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (tnuo *TeamNotificationUpdateOne) SetUpdatedAt(t time.Time) *TeamNotificationUpdateOne {
	tnuo.mutation.SetUpdatedAt(t)
	return tnuo
}

// SetDeletedAt sets the "deleted_at" field.
func (tnuo *TeamNotificationUpdateOne) SetDeletedAt(t time.Time) *TeamNotificationUpdateOne {
	tnuo.mutation.SetDeletedAt(t)
	return tnuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableDeletedAt(t *time.Time) *TeamNotificationUpdateOne {
	if t != nil {
		tnuo.SetDeletedAt(*t)
	}
	return tnuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tnuo *TeamNotificationUpdateOne) ClearDeletedAt() *TeamNotificationUpdateOne {
	tnuo.mutation.ClearDeletedAt()
	return tnuo
}

// SetUserID sets the "user_id" field.
func (tnuo *TeamNotificationUpdateOne) SetUserID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.ResetUserID()
	tnuo.mutation.SetUserID(i)
	return tnuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableUserID(i *int) *TeamNotificationUpdateOne {
	if i != nil {
		tnuo.SetUserID(*i)
	}
	return tnuo
}

// AddUserID adds i to the "user_id" field.
func (tnuo *TeamNotificationUpdateOne) AddUserID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.AddUserID(i)
	return tnuo
}

// SetActorID sets the "actor_id" field.
func (tnuo *TeamNotificationUpdateOne) SetActorID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.ResetActorID()
	tnuo.mutation.SetActorID(i)
	return tnuo
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableActorID(i *int) *TeamNotificationUpdateOne {
	if i != nil {
		tnuo.SetActorID(*i)
	}
	return tnuo
}

// AddActorID adds i to the "actor_id" field.
func (tnuo *TeamNotificationUpdateOne) AddActorID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.AddActorID(i)
	return tnuo
}

// ClearActorID clears the value of the "actor_id" field.
func (tnuo *TeamNotificationUpdateOne) ClearActorID() *TeamNotificationUpdateOne {
	tnuo.mutation.ClearActorID()
	return tnuo
}

// SetType sets the "type" field.
func (tnuo *TeamNotificationUpdateOne) SetType(s string) *TeamNotificationUpdateOne {
	tnuo.mutation.SetType(s)
	return tnuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableType(s *string) *TeamNotificationUpdateOne {
	if s != nil {
		tnuo.SetType(*s)
	}
	return tnuo
}

// SetProjectID sets the "project_id" field.
func (tnuo *TeamNotificationUpdateOne) SetProjectID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.ResetProjectID()
	tnuo.mutation.SetProjectID(i)
	return tnuo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableProjectID(i *int) *TeamNotificationUpdateOne {
	if i != nil {
		tnuo.SetProjectID(*i)
	}
	return tnuo
}

// AddProjectID adds i to the "project_id" field.
func (tnuo *TeamNotificationUpdateOne) AddProjectID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.AddProjectID(i)
	return tnuo
}

// ClearProjectID clears the value of the "project_id" field.
func (tnuo *TeamNotificationUpdateOne) ClearProjectID() *TeamNotificationUpdateOne {
	tnuo.mutation.ClearProjectID()
	return tnuo
}

// SetTaskID sets the "task_id" field.
func (tnuo *TeamNotificationUpdateOne) SetTaskID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.ResetTaskID()
	tnuo.mutation.SetTaskID(i)
	return tnuo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableTaskID(i *int) *TeamNotificationUpdateOne {
	if i != nil {
		tnuo.SetTaskID(*i)
	}
	return tnuo
}

// AddTaskID adds i to the "task_id" field.
func (tnuo *TeamNotificationUpdateOne) AddTaskID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.AddTaskID(i)
	return tnuo
}

// ClearTaskID clears the value of the "task_id" field.
func (tnuo *TeamNotificationUpdateOne) ClearTaskID() *TeamNotificationUpdateOne {
	tnuo.mutation.ClearTaskID()
	return tnuo
}

// SetDocID sets the "doc_id" field.
func (tnuo *TeamNotificationUpdateOne) SetDocID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.ResetDocID()
	tnuo.mutation.SetDocID(i)
	return tnuo
}

// SetNillableDocID sets the "doc_id" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableDocID(i *int) *TeamNotificationUpdateOne {
	if i != nil {
		tnuo.SetDocID(*i)
	}
	return tnuo
}

// AddDocID adds i to the "doc_id" field.
func (tnuo *TeamNotificationUpdateOne) AddDocID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.AddDocID(i)
	return tnuo
}

// ClearDocID clears the value of the "doc_id" field.
func (tnuo *TeamNotificationUpdateOne) ClearDocID() *TeamNotificationUpdateOne {
	tnuo.mutation.ClearDocID()
	return tnuo
}

// SetTopicID sets the "topic_id" field.
func (tnuo *TeamNotificationUpdateOne) SetTopicID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.ResetTopicID()
	tnuo.mutation.SetTopicID(i)
	return tnuo
}

// SetNillableTopicID sets the "topic_id" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableTopicID(i *int) *TeamNotificationUpdateOne {
	if i != nil {
		tnuo.SetTopicID(*i)
	}
	return tnuo
}

// AddTopicID adds i to the "topic_id" field.
func (tnuo *TeamNotificationUpdateOne) AddTopicID(i int) *TeamNotificationUpdateOne {
	tnuo.mutation.AddTopicID(i)
	return tnuo
}

// ClearTopicID clears the value of the "topic_id" field.
func (tnuo *TeamNotificationUpdateOne) ClearTopicID() *TeamNotificationUpdateOne {
	tnuo.mutation.ClearTopicID()
	return tnuo
}

// SetTitle sets the "title" field.
func (tnuo *TeamNotificationUpdateOne) SetTitle(s string) *TeamNotificationUpdateOne {
	tnuo.mutation.SetTitle(s)
	return tnuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableTitle(s *string) *TeamNotificationUpdateOne {
	if s != nil {
		tnuo.SetTitle(*s)
	}
	return tnuo
}

// SetBody sets the "body" field.
func (tnuo *TeamNotificationUpdateOne) SetBody(s string) *TeamNotificationUpdateOne {
	tnuo.mutation.SetBody(s)
	return tnuo
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableBody(s *string) *TeamNotificationUpdateOne {
	if s != nil {
		tnuo.SetBody(*s)
	}
	return tnuo
}

// ClearBody clears the value of the "body" field.
func (tnuo *TeamNotificationUpdateOne) ClearBody() *TeamNotificationUpdateOne {
	tnuo.mutation.ClearBody()
	return tnuo
}

// SetIsRead sets the "is_read" field.
func (tnuo *TeamNotificationUpdateOne) SetIsRead(b bool) *TeamNotificationUpdateOne {
	tnuo.mutation.SetIsRead(b)
	return tnuo
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (tnuo *TeamNotificationUpdateOne) SetNillableIsRead(b *bool) *TeamNotificationUpdateOne {
	if b != nil {
		tnuo.SetIsRead(*b)
	}
	return tnuo
}

// Mutation returns the TeamNotificationMutation object of the builder.
func (tnuo *TeamNotificationUpdateOne) Mutation() *TeamNotificationMutation {
	return tnuo.mutation
}

// Where appends a list predicates to the TeamNotificationUpdate builder.
func (tnuo *TeamNotificationUpdateOne) Where(ps ...predicate.TeamNotification) *TeamNotificationUpdateOne {
	tnuo.mutation.Where(ps...)
	return tnuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tnuo *TeamNotificationUpdateOne) Select(field string, fields ...string) *TeamNotificationUpdateOne {
	tnuo.fields = append([]string{field}, fields...)
	return tnuo
}

// Save executes the query and returns the updated TeamNotification entity.
func (tnuo *TeamNotificationUpdateOne) Save(ctx context.Context) (*TeamNotification, error) {
	if err := tnuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, tnuo.sqlSave, tnuo.mutation, tnuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tnuo *TeamNotificationUpdateOne) SaveX(ctx context.Context) *TeamNotification {
	node, err := tnuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tnuo *TeamNotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := tnuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tnuo *TeamNotificationUpdateOne) ExecX(ctx context.Context) {
	if err := tnuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tnuo *TeamNotificationUpdateOne) defaults() error {
	if _, ok := tnuo.mutation.UpdatedAt(); !ok {
		if teamnotification.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamnotification.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamnotification.UpdateDefaultUpdatedAt()
		tnuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tnuo *TeamNotificationUpdateOne) check() error {
	if v, ok := tnuo.mutation.GetType(); ok {
		if err := teamnotification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TeamNotification.type": %w`, err)}
		}
	}
	if v, ok := tnuo.mutation.Title(); ok {
		if err := teamnotification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TeamNotification.title": %w`, err)}
		}
	}
	return nil
}

func (tnuo *TeamNotificationUpdateOne) sqlSave(ctx context.Context) (_node *TeamNotification, err error) {
	if err := tnuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamnotification.Table, teamnotification.Columns, sqlgraph.NewFieldSpec(teamnotification.FieldID, field.TypeInt))
	id, ok := tnuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamNotification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tnuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamnotification.FieldID)
		for _, f := range fields {
			if !teamnotification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamnotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tnuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tnuo.mutation.UpdatedAt(); ok {
		_spec.SetField(teamnotification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tnuo.mutation.DeletedAt(); ok {
		_spec.SetField(teamnotification.FieldDeletedAt, field.TypeTime, value)
	}
	if tnuo.mutation.DeletedAtCleared() {
		_spec.ClearField(teamnotification.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := tnuo.mutation.UserID(); ok {
		_spec.SetField(teamnotification.FieldUserID, field.TypeInt, value)
	}
	if value, ok := tnuo.mutation.AddedUserID(); ok {
		_spec.AddField(teamnotification.FieldUserID, field.TypeInt, value)
	}
	if value, ok := tnuo.mutation.ActorID(); ok {
		_spec.SetField(teamnotification.FieldActorID, field.TypeInt, value)
	}
	if value, ok := tnuo.mutation.AddedActorID(); ok {
		_spec.AddField(teamnotification.FieldActorID, field.TypeInt, value)
	}
	if tnuo.mutation.ActorIDCleared() {
		_spec.ClearField(teamnotification.FieldActorID, field.TypeInt)
	}
	if value, ok := tnuo.mutation.GetType(); ok {
		_spec.SetField(teamnotification.FieldType, field.TypeString, value)
	}
	if value, ok := tnuo.mutation.ProjectID(); ok {
		_spec.SetField(teamnotification.FieldProjectID, field.TypeInt, value)
	}
	if value, ok := tnuo.mutation.AddedProjectID(); ok {
		_spec.AddField(teamnotification.FieldProjectID, field.TypeInt, value)
	}
	if tnuo.mutation.ProjectIDCleared() {
		_spec.ClearField(teamnotification.FieldProjectID, field.TypeInt)
	}
	if value, ok := tnuo.mutation.TaskID(); ok {
		_spec.SetField(teamnotification.FieldTaskID, field.TypeInt, value)
	}
	if value, ok := tnuo.mutation.AddedTaskID(); ok {
		_spec.AddField(teamnotification.FieldTaskID, field.TypeInt, value)
	}
	if tnuo.mutation.TaskIDCleared() {
		_spec.ClearField(teamnotification.FieldTaskID, field.TypeInt)
	}
	if value, ok := tnuo.mutation.DocID(); ok {
		_spec.SetField(teamnotification.FieldDocID, field.TypeInt, value)
	}
	if value, ok := tnuo.mutation.AddedDocID(); ok {
		_spec.AddField(teamnotification.FieldDocID, field.TypeInt, value)
	}
	if tnuo.mutation.DocIDCleared() {
		_spec.ClearField(teamnotification.FieldDocID, field.TypeInt)
	}
	if value, ok := tnuo.mutation.TopicID(); ok {
		_spec.SetField(teamnotification.FieldTopicID, field.TypeInt, value)
	}
	if value, ok := tnuo.mutation.AddedTopicID(); ok {
		_spec.AddField(teamnotification.FieldTopicID, field.TypeInt, value)
	}
	if tnuo.mutation.TopicIDCleared() {
		_spec.ClearField(teamnotification.FieldTopicID, field.TypeInt)
	}
	if value, ok := tnuo.mutation.Title(); ok {
		_spec.SetField(teamnotification.FieldTitle, field.TypeString, value)
	}
	if value, ok := tnuo.mutation.Body(); ok {
		_spec.SetField(teamnotification.FieldBody, field.TypeString, value)
	}
	if tnuo.mutation.BodyCleared() {
		_spec.ClearField(teamnotification.FieldBody, field.TypeString)
	}
	if value, ok := tnuo.mutation.IsRead(); ok {
		_spec.SetField(teamnotification.FieldIsRead, field.TypeBool, value)
	}
	_node = &TeamNotification{config: tnuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tnuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tnuo.mutation.done = true
	return _node, nil
}
