// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtopic"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtopicattachment"
)

// TeamTopicAttachmentCreate is the builder for creating a TeamTopicAttachment entity.
type TeamTopicAttachmentCreate struct {
	config
	mutation *TeamTopicAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ttac *TeamTopicAttachmentCreate) SetCreatedAt(t time.Time) *TeamTopicAttachmentCreate {
	ttac.mutation.SetCreatedAt(t)
	return ttac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ttac *TeamTopicAttachmentCreate) SetNillableCreatedAt(t *time.Time) *TeamTopicAttachmentCreate {
	if t != nil {
		ttac.SetCreatedAt(*t)
	}
	return ttac
}

// SetUpdatedAt sets the "updated_at" field.
func (ttac *TeamTopicAttachmentCreate) SetUpdatedAt(t time.Time) *TeamTopicAttachmentCreate {
	ttac.mutation.SetUpdatedAt(t)
	return ttac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ttac *TeamTopicAttachmentCreate) SetNillableUpdatedAt(t *time.Time) *TeamTopicAttachmentCreate {
	if t != nil {
		ttac.SetUpdatedAt(*t)
	}
	return ttac
}

// SetDeletedAt sets the "deleted_at" field.
func (ttac *TeamTopicAttachmentCreate) SetDeletedAt(t time.Time) *TeamTopicAttachmentCreate {
	ttac.mutation.SetDeletedAt(t)
	return ttac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ttac *TeamTopicAttachmentCreate) SetNillableDeletedAt(t *time.Time) *TeamTopicAttachmentCreate {
	if t != nil {
		ttac.SetDeletedAt(*t)
	}
	return ttac
}

// SetTopicID sets the "topic_id" field.
func (ttac *TeamTopicAttachmentCreate) SetTopicID(i int) *TeamTopicAttachmentCreate {
	ttac.mutation.SetTopicID(i)
	return ttac
}

// SetUserID sets the "user_id" field.
func (ttac *TeamTopicAttachmentCreate) SetUserID(i int) *TeamTopicAttachmentCreate {
	ttac.mutation.SetUserID(i)
	return ttac
}

// SetFileID sets the "file_id" field.
func (ttac *TeamTopicAttachmentCreate) SetFileID(i int) *TeamTopicAttachmentCreate {
	ttac.mutation.SetFileID(i)
	return ttac
}

// SetName sets the "name" field.
func (ttac *TeamTopicAttachmentCreate) SetName(s string) *TeamTopicAttachmentCreate {
	ttac.mutation.SetName(s)
	return ttac
}

// SetSize sets the "size" field.
func (ttac *TeamTopicAttachmentCreate) SetSize(i int64) *TeamTopicAttachmentCreate {
	ttac.mutation.SetSize(i)
	return ttac
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (ttac *TeamTopicAttachmentCreate) SetNillableSize(i *int64) *TeamTopicAttachmentCreate {
	if i != nil {
		ttac.SetSize(*i)
	}
	return ttac
}

// SetTopic sets the "topic" edge to the TeamTopic entity.
func (ttac *TeamTopicAttachmentCreate) SetTopic(t *TeamTopic) *TeamTopicAttachmentCreate {
	return ttac.SetTopicID(t.ID)
}

// Mutation returns the TeamTopicAttachmentMutation object of the builder.
func (ttac *TeamTopicAttachmentCreate) Mutation() *TeamTopicAttachmentMutation {
	return ttac.mutation
}

// Save creates the TeamTopicAttachment in the database.
func (ttac *TeamTopicAttachmentCreate) Save(ctx context.Context) (*TeamTopicAttachment, error) {
	if err := ttac.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ttac.sqlSave, ttac.mutation, ttac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ttac *TeamTopicAttachmentCreate) SaveX(ctx context.Context) *TeamTopicAttachment {
	v, err := ttac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttac *TeamTopicAttachmentCreate) Exec(ctx context.Context) error {
	_, err := ttac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttac *TeamTopicAttachmentCreate) ExecX(ctx context.Context) {
	if err := ttac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ttac *TeamTopicAttachmentCreate) defaults() error {
	if _, ok := ttac.mutation.CreatedAt(); !ok {
		if teamtopicattachment.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamtopicattachment.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := teamtopicattachment.DefaultCreatedAt()
		ttac.mutation.SetCreatedAt(v)
	}
	if _, ok := ttac.mutation.UpdatedAt(); !ok {
		if teamtopicattachment.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized teamtopicattachment.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := teamtopicattachment.DefaultUpdatedAt()
		ttac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ttac.mutation.Size(); !ok {
		v := teamtopicattachment.DefaultSize
		ttac.mutation.SetSize(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ttac *TeamTopicAttachmentCreate) check() error {
	if _, ok := ttac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamTopicAttachment.created_at"`)}
	}
	if _, ok := ttac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamTopicAttachment.updated_at"`)}
	}
	if _, ok := ttac.mutation.TopicID(); !ok {
		return &ValidationError{Name: "topic_id", err: errors.New(`ent: missing required field "TeamTopicAttachment.topic_id"`)}
	}
	if _, ok := ttac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TeamTopicAttachment.user_id"`)}
	}
	if _, ok := ttac.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "TeamTopicAttachment.file_id"`)}
	}
	if _, ok := ttac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TeamTopicAttachment.name"`)}
	}
	if v, ok := ttac.mutation.Name(); ok {
		if err := teamtopicattachment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TeamTopicAttachment.name": %w`, err)}
		}
	}
	if _, ok := ttac.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "TeamTopicAttachment.size"`)}
	}
	if _, ok := ttac.mutation.TopicID(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required edge "TeamTopicAttachment.topic"`)}
	}
	return nil
}

func (ttac *TeamTopicAttachmentCreate) sqlSave(ctx context.Context) (*TeamTopicAttachment, error) {
	if err := ttac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ttac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ttac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ttac.mutation.id = &_node.ID
	ttac.mutation.done = true
	return _node, nil
}

func (ttac *TeamTopicAttachmentCreate) createSpec() (*TeamTopicAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamTopicAttachment{config: ttac.config}
		_spec = sqlgraph.NewCreateSpec(teamtopicattachment.Table, sqlgraph.NewFieldSpec(teamtopicattachment.FieldID, field.TypeInt))
	)

	if id, ok := ttac.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = ttac.conflict
	if value, ok := ttac.mutation.CreatedAt(); ok {
		_spec.SetField(teamtopicattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ttac.mutation.UpdatedAt(); ok {
		_spec.SetField(teamtopicattachment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ttac.mutation.DeletedAt(); ok {
		_spec.SetField(teamtopicattachment.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := ttac.mutation.UserID(); ok {
		_spec.SetField(teamtopicattachment.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := ttac.mutation.FileID(); ok {
		_spec.SetField(teamtopicattachment.FieldFileID, field.TypeInt, value)
		_node.FileID = value
	}
	if value, ok := ttac.mutation.Name(); ok {
		_spec.SetField(teamtopicattachment.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ttac.mutation.Size(); ok {
		_spec.SetField(teamtopicattachment.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if nodes := ttac.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtopicattachment.TopicTable,
			Columns: []string{teamtopicattachment.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamtopic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TopicID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamTopicAttachment.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamTopicAttachmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ttac *TeamTopicAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *TeamTopicAttachmentUpsertOne {
	ttac.conflict = opts
	return &TeamTopicAttachmentUpsertOne{
		create: ttac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamTopicAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ttac *TeamTopicAttachmentCreate) OnConflictColumns(columns ...string) *TeamTopicAttachmentUpsertOne {
	ttac.conflict = append(ttac.conflict, sql.ConflictColumns(columns...))
	return &TeamTopicAttachmentUpsertOne{
		create: ttac,
	}
}

type (
	// TeamTopicAttachmentUpsertOne is the builder for "upsert"-ing
	//  one TeamTopicAttachment node.
	TeamTopicAttachmentUpsertOne struct {
		create *TeamTopicAttachmentCreate
	}

	// TeamTopicAttachmentUpsert is the "OnConflict" setter.
	TeamTopicAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamTopicAttachmentUpsert) SetUpdatedAt(v time.Time) *TeamTopicAttachmentUpsert {
	u.Set(teamtopicattachment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsert) UpdateUpdatedAt() *TeamTopicAttachmentUpsert {
	u.SetExcluded(teamtopicattachment.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamTopicAttachmentUpsert) SetDeletedAt(v time.Time) *TeamTopicAttachmentUpsert {
	u.Set(teamtopicattachment.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsert) UpdateDeletedAt() *TeamTopicAttachmentUpsert {
	u.SetExcluded(teamtopicattachment.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamTopicAttachmentUpsert) ClearDeletedAt() *TeamTopicAttachmentUpsert {
	u.SetNull(teamtopicattachment.FieldDeletedAt)
	return u
}

// SetTopicID sets the "topic_id" field.
func (u *TeamTopicAttachmentUpsert) SetTopicID(v int) *TeamTopicAttachmentUpsert {
	u.Set(teamtopicattachment.FieldTopicID, v)
	return u
}

// UpdateTopicID sets the "topic_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsert) UpdateTopicID() *TeamTopicAttachmentUpsert {
	u.SetExcluded(teamtopicattachment.FieldTopicID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TeamTopicAttachmentUpsert) SetUserID(v int) *TeamTopicAttachmentUpsert {
	u.Set(teamtopicattachment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsert) UpdateUserID() *TeamTopicAttachmentUpsert {
	u.SetExcluded(teamtopicattachment.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *TeamTopicAttachmentUpsert) AddUserID(v int) *TeamTopicAttachmentUpsert {
	u.Add(teamtopicattachment.FieldUserID, v)
	return u
}

// SetFileID sets the "file_id" field.
func (u *TeamTopicAttachmentUpsert) SetFileID(v int) *TeamTopicAttachmentUpsert {
	u.Set(teamtopicattachment.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsert) UpdateFileID() *TeamTopicAttachmentUpsert {
	u.SetExcluded(teamtopicattachment.FieldFileID)
	return u
}

// AddFileID adds v to the "file_id" field.
func (u *TeamTopicAttachmentUpsert) AddFileID(v int) *TeamTopicAttachmentUpsert {
	u.Add(teamtopicattachment.FieldFileID, v)
	return u
}

// SetName sets the "name" field.
func (u *TeamTopicAttachmentUpsert) SetName(v string) *TeamTopicAttachmentUpsert {
	u.Set(teamtopicattachment.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsert) UpdateName() *TeamTopicAttachmentUpsert {
	u.SetExcluded(teamtopicattachment.FieldName)
	return u
}

// SetSize sets the "size" field.
func (u *TeamTopicAttachmentUpsert) SetSize(v int64) *TeamTopicAttachmentUpsert {
	u.Set(teamtopicattachment.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsert) UpdateSize() *TeamTopicAttachmentUpsert {
	u.SetExcluded(teamtopicattachment.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *TeamTopicAttachmentUpsert) AddSize(v int64) *TeamTopicAttachmentUpsert {
	u.Add(teamtopicattachment.FieldSize, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamTopicAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamTopicAttachmentUpsertOne) UpdateNewValues() *TeamTopicAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teamtopicattachment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamTopicAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamTopicAttachmentUpsertOne) Ignore() *TeamTopicAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamTopicAttachmentUpsertOne) DoNothing() *TeamTopicAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamTopicAttachmentCreate.OnConflict
// documentation for more info.
func (u *TeamTopicAttachmentUpsertOne) Update(set func(*TeamTopicAttachmentUpsert)) *TeamTopicAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamTopicAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamTopicAttachmentUpsertOne) SetUpdatedAt(v time.Time) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertOne) UpdateUpdatedAt() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamTopicAttachmentUpsertOne) SetDeletedAt(v time.Time) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertOne) UpdateDeletedAt() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamTopicAttachmentUpsertOne) ClearDeletedAt() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTopicID sets the "topic_id" field.
func (u *TeamTopicAttachmentUpsertOne) SetTopicID(v int) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetTopicID(v)
	})
}

// UpdateTopicID sets the "topic_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertOne) UpdateTopicID() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateTopicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamTopicAttachmentUpsertOne) SetUserID(v int) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *TeamTopicAttachmentUpsertOne) AddUserID(v int) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertOne) UpdateUserID() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateUserID()
	})
}

// SetFileID sets the "file_id" field.
func (u *TeamTopicAttachmentUpsertOne) SetFileID(v int) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *TeamTopicAttachmentUpsertOne) AddFileID(v int) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertOne) UpdateFileID() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateFileID()
	})
}

// SetName sets the "name" field.
func (u *TeamTopicAttachmentUpsertOne) SetName(v string) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertOne) UpdateName() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateName()
	})
}

// SetSize sets the "size" field.
func (u *TeamTopicAttachmentUpsertOne) SetSize(v int64) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *TeamTopicAttachmentUpsertOne) AddSize(v int64) *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertOne) UpdateSize() *TeamTopicAttachmentUpsertOne {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateSize()
	})
}

// Exec executes the query.
func (u *TeamTopicAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamTopicAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamTopicAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamTopicAttachmentUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamTopicAttachmentUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *TeamTopicAttachmentCreate) SetRawID(t int) *TeamTopicAttachmentCreate {
	m.mutation.SetRawID(t)
	return m
}

// TeamTopicAttachmentCreateBulk is the builder for creating many TeamTopicAttachment entities in bulk.
type TeamTopicAttachmentCreateBulk struct {
	config
	err      error
	builders []*TeamTopicAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamTopicAttachment entities in the database.
func (ttacb *TeamTopicAttachmentCreateBulk) Save(ctx context.Context) ([]*TeamTopicAttachment, error) {
	if ttacb.err != nil {
		return nil, ttacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ttacb.builders))
	nodes := make([]*TeamTopicAttachment, len(ttacb.builders))
	mutators := make([]Mutator, len(ttacb.builders))
	for i := range ttacb.builders {
		func(i int, root context.Context) {
			builder := ttacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamTopicAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ttacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ttacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ttacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ttacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ttacb *TeamTopicAttachmentCreateBulk) SaveX(ctx context.Context) []*TeamTopicAttachment {
	v, err := ttacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttacb *TeamTopicAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := ttacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttacb *TeamTopicAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := ttacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamTopicAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamTopicAttachmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ttacb *TeamTopicAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamTopicAttachmentUpsertBulk {
	ttacb.conflict = opts
	return &TeamTopicAttachmentUpsertBulk{
		create: ttacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamTopicAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ttacb *TeamTopicAttachmentCreateBulk) OnConflictColumns(columns ...string) *TeamTopicAttachmentUpsertBulk {
	ttacb.conflict = append(ttacb.conflict, sql.ConflictColumns(columns...))
	return &TeamTopicAttachmentUpsertBulk{
		create: ttacb,
	}
}

// TeamTopicAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamTopicAttachment nodes.
type TeamTopicAttachmentUpsertBulk struct {
	create *TeamTopicAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamTopicAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamTopicAttachmentUpsertBulk) UpdateNewValues() *TeamTopicAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teamtopicattachment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamTopicAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamTopicAttachmentUpsertBulk) Ignore() *TeamTopicAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamTopicAttachmentUpsertBulk) DoNothing() *TeamTopicAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamTopicAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *TeamTopicAttachmentUpsertBulk) Update(set func(*TeamTopicAttachmentUpsert)) *TeamTopicAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamTopicAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamTopicAttachmentUpsertBulk) SetUpdatedAt(v time.Time) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertBulk) UpdateUpdatedAt() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TeamTopicAttachmentUpsertBulk) SetDeletedAt(v time.Time) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertBulk) UpdateDeletedAt() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TeamTopicAttachmentUpsertBulk) ClearDeletedAt() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetTopicID sets the "topic_id" field.
func (u *TeamTopicAttachmentUpsertBulk) SetTopicID(v int) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetTopicID(v)
	})
}

// UpdateTopicID sets the "topic_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertBulk) UpdateTopicID() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateTopicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamTopicAttachmentUpsertBulk) SetUserID(v int) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *TeamTopicAttachmentUpsertBulk) AddUserID(v int) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertBulk) UpdateUserID() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateUserID()
	})
}

// SetFileID sets the "file_id" field.
func (u *TeamTopicAttachmentUpsertBulk) SetFileID(v int) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *TeamTopicAttachmentUpsertBulk) AddFileID(v int) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertBulk) UpdateFileID() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateFileID()
	})
}

// SetName sets the "name" field.
func (u *TeamTopicAttachmentUpsertBulk) SetName(v string) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertBulk) UpdateName() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateName()
	})
}

// SetSize sets the "size" field.
func (u *TeamTopicAttachmentUpsertBulk) SetSize(v int64) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *TeamTopicAttachmentUpsertBulk) AddSize(v int64) *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *TeamTopicAttachmentUpsertBulk) UpdateSize() *TeamTopicAttachmentUpsertBulk {
	return u.Update(func(s *TeamTopicAttachmentUpsert) {
		s.UpdateSize()
	})
}

// Exec executes the query.
func (u *TeamTopicAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamTopicAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamTopicAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamTopicAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
