// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtask"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtaskcollaborator"
)

// TeamTaskCollaboratorQuery is the builder for querying TeamTaskCollaborator entities.
type TeamTaskCollaboratorQuery struct {
	config
	ctx        *QueryContext
	order      []teamtaskcollaborator.OrderOption
	inters     []Interceptor
	predicates []predicate.TeamTaskCollaborator
	withTask   *TeamTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamTaskCollaboratorQuery builder.
func (ttcq *TeamTaskCollaboratorQuery) Where(ps ...predicate.TeamTaskCollaborator) *TeamTaskCollaboratorQuery {
	ttcq.predicates = append(ttcq.predicates, ps...)
	return ttcq
}

// Limit the number of records to be returned by this query.
func (ttcq *TeamTaskCollaboratorQuery) Limit(limit int) *TeamTaskCollaboratorQuery {
	ttcq.ctx.Limit = &limit
	return ttcq
}

// Offset to start from.
func (ttcq *TeamTaskCollaboratorQuery) Offset(offset int) *TeamTaskCollaboratorQuery {
	ttcq.ctx.Offset = &offset
	return ttcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ttcq *TeamTaskCollaboratorQuery) Unique(unique bool) *TeamTaskCollaboratorQuery {
	ttcq.ctx.Unique = &unique
	return ttcq
}

// Order specifies how the records should be ordered.
func (ttcq *TeamTaskCollaboratorQuery) Order(o ...teamtaskcollaborator.OrderOption) *TeamTaskCollaboratorQuery {
	ttcq.order = append(ttcq.order, o...)
	return ttcq
}

// QueryTask chains the current query on the "task" edge.
func (ttcq *TeamTaskCollaboratorQuery) QueryTask() *TeamTaskQuery {
	query := (&TeamTaskClient{config: ttcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ttcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ttcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamtaskcollaborator.Table, teamtaskcollaborator.FieldID, selector),
			sqlgraph.To(teamtask.Table, teamtask.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, teamtaskcollaborator.TaskTable, teamtaskcollaborator.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(ttcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TeamTaskCollaborator entity from the query.
// Returns a *NotFoundError when no TeamTaskCollaborator was found.
func (ttcq *TeamTaskCollaboratorQuery) First(ctx context.Context) (*TeamTaskCollaborator, error) {
	nodes, err := ttcq.Limit(1).All(setContextOp(ctx, ttcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teamtaskcollaborator.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) FirstX(ctx context.Context) *TeamTaskCollaborator {
	node, err := ttcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamTaskCollaborator ID from the query.
// Returns a *NotFoundError when no TeamTaskCollaborator ID was found.
func (ttcq *TeamTaskCollaboratorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttcq.Limit(1).IDs(setContextOp(ctx, ttcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teamtaskcollaborator.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) FirstIDX(ctx context.Context) int {
	id, err := ttcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamTaskCollaborator entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TeamTaskCollaborator entity is found.
// Returns a *NotFoundError when no TeamTaskCollaborator entities are found.
func (ttcq *TeamTaskCollaboratorQuery) Only(ctx context.Context) (*TeamTaskCollaborator, error) {
	nodes, err := ttcq.Limit(2).All(setContextOp(ctx, ttcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teamtaskcollaborator.Label}
	default:
		return nil, &NotSingularError{teamtaskcollaborator.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) OnlyX(ctx context.Context) *TeamTaskCollaborator {
	node, err := ttcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamTaskCollaborator ID in the query.
// Returns a *NotSingularError when more than one TeamTaskCollaborator ID is found.
// Returns a *NotFoundError when no entities are found.
func (ttcq *TeamTaskCollaboratorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttcq.Limit(2).IDs(setContextOp(ctx, ttcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teamtaskcollaborator.Label}
	default:
		err = &NotSingularError{teamtaskcollaborator.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) OnlyIDX(ctx context.Context) int {
	id, err := ttcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamTaskCollaborators.
func (ttcq *TeamTaskCollaboratorQuery) All(ctx context.Context) ([]*TeamTaskCollaborator, error) {
	ctx = setContextOp(ctx, ttcq.ctx, "All")
	if err := ttcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TeamTaskCollaborator, *TeamTaskCollaboratorQuery]()
	return withInterceptors[[]*TeamTaskCollaborator](ctx, ttcq, qr, ttcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) AllX(ctx context.Context) []*TeamTaskCollaborator {
	nodes, err := ttcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamTaskCollaborator IDs.
func (ttcq *TeamTaskCollaboratorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ttcq.ctx.Unique == nil && ttcq.path != nil {
		ttcq.Unique(true)
	}
	ctx = setContextOp(ctx, ttcq.ctx, "IDs")
	if err = ttcq.Select(teamtaskcollaborator.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) IDsX(ctx context.Context) []int {
	ids, err := ttcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ttcq *TeamTaskCollaboratorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ttcq.ctx, "Count")
	if err := ttcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ttcq, querierCount[*TeamTaskCollaboratorQuery](), ttcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) CountX(ctx context.Context) int {
	count, err := ttcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ttcq *TeamTaskCollaboratorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ttcq.ctx, "Exist")
	switch _, err := ttcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ttcq *TeamTaskCollaboratorQuery) ExistX(ctx context.Context) bool {
	exist, err := ttcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamTaskCollaboratorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ttcq *TeamTaskCollaboratorQuery) Clone() *TeamTaskCollaboratorQuery {
	if ttcq == nil {
		return nil
	}
	return &TeamTaskCollaboratorQuery{
		config:     ttcq.config,
		ctx:        ttcq.ctx.Clone(),
		order:      append([]teamtaskcollaborator.OrderOption{}, ttcq.order...),
		inters:     append([]Interceptor{}, ttcq.inters...),
		predicates: append([]predicate.TeamTaskCollaborator{}, ttcq.predicates...),
		withTask:   ttcq.withTask.Clone(),
		// clone intermediate query.
		sql:  ttcq.sql.Clone(),
		path: ttcq.path,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (ttcq *TeamTaskCollaboratorQuery) WithTask(opts ...func(*TeamTaskQuery)) *TeamTaskCollaboratorQuery {
	query := (&TeamTaskClient{config: ttcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ttcq.withTask = query
	return ttcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamTaskCollaborator.Query().
//		GroupBy(teamtaskcollaborator.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ttcq *TeamTaskCollaboratorQuery) GroupBy(field string, fields ...string) *TeamTaskCollaboratorGroupBy {
	ttcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeamTaskCollaboratorGroupBy{build: ttcq}
	grbuild.flds = &ttcq.ctx.Fields
	grbuild.label = teamtaskcollaborator.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.TeamTaskCollaborator.Query().
//		Select(teamtaskcollaborator.FieldCreatedAt).
//		Scan(ctx, &v)
func (ttcq *TeamTaskCollaboratorQuery) Select(fields ...string) *TeamTaskCollaboratorSelect {
	ttcq.ctx.Fields = append(ttcq.ctx.Fields, fields...)
	sbuild := &TeamTaskCollaboratorSelect{TeamTaskCollaboratorQuery: ttcq}
	sbuild.label = teamtaskcollaborator.Label
	sbuild.flds, sbuild.scan = &ttcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeamTaskCollaboratorSelect configured with the given aggregations.
func (ttcq *TeamTaskCollaboratorQuery) Aggregate(fns ...AggregateFunc) *TeamTaskCollaboratorSelect {
	return ttcq.Select().Aggregate(fns...)
}

func (ttcq *TeamTaskCollaboratorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ttcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ttcq); err != nil {
				return err
			}
		}
	}
	for _, f := range ttcq.ctx.Fields {
		if !teamtaskcollaborator.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ttcq.path != nil {
		prev, err := ttcq.path(ctx)
		if err != nil {
			return err
		}
		ttcq.sql = prev
	}
	return nil
}

func (ttcq *TeamTaskCollaboratorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TeamTaskCollaborator, error) {
	var (
		nodes       = []*TeamTaskCollaborator{}
		_spec       = ttcq.querySpec()
		loadedTypes = [1]bool{
			ttcq.withTask != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TeamTaskCollaborator).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TeamTaskCollaborator{config: ttcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ttcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ttcq.withTask; query != nil {
		if err := ttcq.loadTask(ctx, query, nodes, nil,
			func(n *TeamTaskCollaborator, e *TeamTask) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ttcq *TeamTaskCollaboratorQuery) loadTask(ctx context.Context, query *TeamTaskQuery, nodes []*TeamTaskCollaborator, init func(*TeamTaskCollaborator), assign func(*TeamTaskCollaborator, *TeamTask)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TeamTaskCollaborator)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(teamtask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ttcq *TeamTaskCollaboratorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ttcq.querySpec()
	_spec.Node.Columns = ttcq.ctx.Fields
	if len(ttcq.ctx.Fields) > 0 {
		_spec.Unique = ttcq.ctx.Unique != nil && *ttcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ttcq.driver, _spec)
}

func (ttcq *TeamTaskCollaboratorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teamtaskcollaborator.Table, teamtaskcollaborator.Columns, sqlgraph.NewFieldSpec(teamtaskcollaborator.FieldID, field.TypeInt))
	_spec.From = ttcq.sql
	if unique := ttcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ttcq.path != nil {
		_spec.Unique = true
	}
	if fields := ttcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamtaskcollaborator.FieldID)
		for i := range fields {
			if fields[i] != teamtaskcollaborator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ttcq.withTask != nil {
			_spec.Node.AddColumnOnce(teamtaskcollaborator.FieldTaskID)
		}
	}
	if ps := ttcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ttcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ttcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ttcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ttcq *TeamTaskCollaboratorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ttcq.driver.Dialect())
	t1 := builder.Table(teamtaskcollaborator.Table)
	columns := ttcq.ctx.Fields
	if len(columns) == 0 {
		columns = teamtaskcollaborator.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ttcq.sql != nil {
		selector = ttcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ttcq.ctx.Unique != nil && *ttcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ttcq.predicates {
		p(selector)
	}
	for _, p := range ttcq.order {
		p(selector)
	}
	if offset := ttcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ttcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TeamTaskCollaboratorGroupBy is the group-by builder for TeamTaskCollaborator entities.
type TeamTaskCollaboratorGroupBy struct {
	selector
	build *TeamTaskCollaboratorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ttcgb *TeamTaskCollaboratorGroupBy) Aggregate(fns ...AggregateFunc) *TeamTaskCollaboratorGroupBy {
	ttcgb.fns = append(ttcgb.fns, fns...)
	return ttcgb
}

// Scan applies the selector query and scans the result into the given value.
func (ttcgb *TeamTaskCollaboratorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ttcgb.build.ctx, "GroupBy")
	if err := ttcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamTaskCollaboratorQuery, *TeamTaskCollaboratorGroupBy](ctx, ttcgb.build, ttcgb, ttcgb.build.inters, v)
}

func (ttcgb *TeamTaskCollaboratorGroupBy) sqlScan(ctx context.Context, root *TeamTaskCollaboratorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ttcgb.fns))
	for _, fn := range ttcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ttcgb.flds)+len(ttcgb.fns))
		for _, f := range *ttcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ttcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ttcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeamTaskCollaboratorSelect is the builder for selecting fields of TeamTaskCollaborator entities.
type TeamTaskCollaboratorSelect struct {
	*TeamTaskCollaboratorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ttcs *TeamTaskCollaboratorSelect) Aggregate(fns ...AggregateFunc) *TeamTaskCollaboratorSelect {
	ttcs.fns = append(ttcs.fns, fns...)
	return ttcs
}

// Scan applies the selector query and scans the result into the given value.
func (ttcs *TeamTaskCollaboratorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ttcs.ctx, "Select")
	if err := ttcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamTaskCollaboratorQuery, *TeamTaskCollaboratorSelect](ctx, ttcs.TeamTaskCollaboratorQuery, ttcs, ttcs.inters, v)
}

func (ttcs *TeamTaskCollaboratorSelect) sqlScan(ctx context.Context, root *TeamTaskCollaboratorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ttcs.fns))
	for _, fn := range ttcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ttcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ttcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
