// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/cloudreve/Cloudreve/v4/ent/davaccount"
	"github.com/cloudreve/Cloudreve/v4/ent/directlink"
	"github.com/cloudreve/Cloudreve/v4/ent/entity"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/filepermission"
	"github.com/cloudreve/Cloudreve/v4/ent/fsevent"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/metadata"
	"github.com/cloudreve/Cloudreve/v4/ent/node"
	"github.com/cloudreve/Cloudreve/v4/ent/oauthclient"
	"github.com/cloudreve/Cloudreve/v4/ent/oauthgrant"
	"github.com/cloudreve/Cloudreve/v4/ent/passkey"
	"github.com/cloudreve/Cloudreve/v4/ent/schema"
	"github.com/cloudreve/Cloudreve/v4/ent/setting"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/storagepolicy"
	"github.com/cloudreve/Cloudreve/v4/ent/task"
	"github.com/cloudreve/Cloudreve/v4/ent/teamactivity"
	"github.com/cloudreve/Cloudreve/v4/ent/teamdoc"
	"github.com/cloudreve/Cloudreve/v4/ent/teammember"
	"github.com/cloudreve/Cloudreve/v4/ent/teamnotification"
	"github.com/cloudreve/Cloudreve/v4/ent/teampost"
	"github.com/cloudreve/Cloudreve/v4/ent/teamproject"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtask"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtaskattachment"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtaskcollaborator"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtaskcomment"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtopic"
	"github.com/cloudreve/Cloudreve/v4/ent/teamtopicattachment"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	davaccountMixin := schema.DavAccount{}.Mixin()
	davaccountMixinHooks0 := davaccountMixin[0].Hooks()
	davaccount.Hooks[0] = davaccountMixinHooks0[0]
	davaccountMixinInters0 := davaccountMixin[0].Interceptors()
	davaccount.Interceptors[0] = davaccountMixinInters0[0]
	davaccountMixinFields0 := davaccountMixin[0].Fields()
	_ = davaccountMixinFields0
	davaccountFields := schema.DavAccount{}.Fields()
	_ = davaccountFields
	// davaccountDescCreatedAt is the schema descriptor for created_at field.
	davaccountDescCreatedAt := davaccountMixinFields0[0].Descriptor()
	// davaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	davaccount.DefaultCreatedAt = davaccountDescCreatedAt.Default.(func() time.Time)
	// davaccountDescUpdatedAt is the schema descriptor for updated_at field.
	davaccountDescUpdatedAt := davaccountMixinFields0[1].Descriptor()
	// davaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	davaccount.DefaultUpdatedAt = davaccountDescUpdatedAt.Default.(func() time.Time)
	// davaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	davaccount.UpdateDefaultUpdatedAt = davaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	directlinkMixin := schema.DirectLink{}.Mixin()
	directlinkMixinHooks0 := directlinkMixin[0].Hooks()
	directlink.Hooks[0] = directlinkMixinHooks0[0]
	directlinkMixinInters0 := directlinkMixin[0].Interceptors()
	directlink.Interceptors[0] = directlinkMixinInters0[0]
	directlinkMixinFields0 := directlinkMixin[0].Fields()
	_ = directlinkMixinFields0
	directlinkFields := schema.DirectLink{}.Fields()
	_ = directlinkFields
	// directlinkDescCreatedAt is the schema descriptor for created_at field.
	directlinkDescCreatedAt := directlinkMixinFields0[0].Descriptor()
	// directlink.DefaultCreatedAt holds the default value on creation for the created_at field.
	directlink.DefaultCreatedAt = directlinkDescCreatedAt.Default.(func() time.Time)
	// directlinkDescUpdatedAt is the schema descriptor for updated_at field.
	directlinkDescUpdatedAt := directlinkMixinFields0[1].Descriptor()
	// directlink.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	directlink.DefaultUpdatedAt = directlinkDescUpdatedAt.Default.(func() time.Time)
	// directlink.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	directlink.UpdateDefaultUpdatedAt = directlinkDescUpdatedAt.UpdateDefault.(func() time.Time)
	entityMixin := schema.Entity{}.Mixin()
	entityMixinHooks0 := entityMixin[0].Hooks()
	entity.Hooks[0] = entityMixinHooks0[0]
	entityMixinInters0 := entityMixin[0].Interceptors()
	entity.Interceptors[0] = entityMixinInters0[0]
	entityMixinFields0 := entityMixin[0].Fields()
	_ = entityMixinFields0
	entityFields := schema.Entity{}.Fields()
	_ = entityFields
	// entityDescCreatedAt is the schema descriptor for created_at field.
	entityDescCreatedAt := entityMixinFields0[0].Descriptor()
	// entity.DefaultCreatedAt holds the default value on creation for the created_at field.
	entity.DefaultCreatedAt = entityDescCreatedAt.Default.(func() time.Time)
	// entityDescUpdatedAt is the schema descriptor for updated_at field.
	entityDescUpdatedAt := entityMixinFields0[1].Descriptor()
	// entity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entity.DefaultUpdatedAt = entityDescUpdatedAt.Default.(func() time.Time)
	// entity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entity.UpdateDefaultUpdatedAt = entityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entityDescReferenceCount is the schema descriptor for reference_count field.
	entityDescReferenceCount := entityFields[3].Descriptor()
	// entity.DefaultReferenceCount holds the default value on creation for the reference_count field.
	entity.DefaultReferenceCount = entityDescReferenceCount.Default.(int)
	fileHooks := schema.File{}.Hooks()
	file.Hooks[0] = fileHooks[0]
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileFields[0].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileFields[1].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// fileDescSize is the schema descriptor for size field.
	fileDescSize := fileFields[5].Descriptor()
	// file.DefaultSize holds the default value on creation for the size field.
	file.DefaultSize = fileDescSize.Default.(int64)
	// fileDescIsSymbolic is the schema descriptor for is_symbolic field.
	fileDescIsSymbolic := fileFields[8].Descriptor()
	// file.DefaultIsSymbolic holds the default value on creation for the is_symbolic field.
	file.DefaultIsSymbolic = fileDescIsSymbolic.Default.(bool)
	filepermissionMixin := schema.FilePermission{}.Mixin()
	filepermissionMixinHooks0 := filepermissionMixin[0].Hooks()
	filepermission.Hooks[0] = filepermissionMixinHooks0[0]
	filepermissionMixinInters0 := filepermissionMixin[0].Interceptors()
	filepermission.Interceptors[0] = filepermissionMixinInters0[0]
	filepermissionMixinFields0 := filepermissionMixin[0].Fields()
	_ = filepermissionMixinFields0
	filepermissionFields := schema.FilePermission{}.Fields()
	_ = filepermissionFields
	// filepermissionDescCreatedAt is the schema descriptor for created_at field.
	filepermissionDescCreatedAt := filepermissionMixinFields0[0].Descriptor()
	// filepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	filepermission.DefaultCreatedAt = filepermissionDescCreatedAt.Default.(func() time.Time)
	// filepermissionDescUpdatedAt is the schema descriptor for updated_at field.
	filepermissionDescUpdatedAt := filepermissionMixinFields0[1].Descriptor()
	// filepermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	filepermission.DefaultUpdatedAt = filepermissionDescUpdatedAt.Default.(func() time.Time)
	// filepermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	filepermission.UpdateDefaultUpdatedAt = filepermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// filepermissionDescSubjectType is the schema descriptor for subject_type field.
	filepermissionDescSubjectType := filepermissionFields[1].Descriptor()
	// filepermission.SubjectTypeValidator is a validator for the "subject_type" field. It is called by the builders before save.
	filepermission.SubjectTypeValidator = filepermissionDescSubjectType.Validators[0].(func(string) error)
	// filepermissionDescPermission is the schema descriptor for permission field.
	filepermissionDescPermission := filepermissionFields[3].Descriptor()
	// filepermission.PermissionValidator is a validator for the "permission" field. It is called by the builders before save.
	filepermission.PermissionValidator = filepermissionDescPermission.Validators[0].(func(string) error)
	// filepermissionDescInherit is the schema descriptor for inherit field.
	filepermissionDescInherit := filepermissionFields[4].Descriptor()
	// filepermission.DefaultInherit holds the default value on creation for the inherit field.
	filepermission.DefaultInherit = filepermissionDescInherit.Default.(bool)
	fseventMixin := schema.FsEvent{}.Mixin()
	fseventMixinHooks0 := fseventMixin[0].Hooks()
	fsevent.Hooks[0] = fseventMixinHooks0[0]
	fseventMixinInters0 := fseventMixin[0].Interceptors()
	fsevent.Interceptors[0] = fseventMixinInters0[0]
	fseventMixinFields0 := fseventMixin[0].Fields()
	_ = fseventMixinFields0
	fseventFields := schema.FsEvent{}.Fields()
	_ = fseventFields
	// fseventDescCreatedAt is the schema descriptor for created_at field.
	fseventDescCreatedAt := fseventMixinFields0[0].Descriptor()
	// fsevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	fsevent.DefaultCreatedAt = fseventDescCreatedAt.Default.(func() time.Time)
	// fseventDescUpdatedAt is the schema descriptor for updated_at field.
	fseventDescUpdatedAt := fseventMixinFields0[1].Descriptor()
	// fsevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fsevent.DefaultUpdatedAt = fseventDescUpdatedAt.Default.(func() time.Time)
	// fsevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fsevent.UpdateDefaultUpdatedAt = fseventDescUpdatedAt.UpdateDefault.(func() time.Time)
	groupMixin := schema.Group{}.Mixin()
	groupMixinHooks0 := groupMixin[0].Hooks()
	group.Hooks[0] = groupMixinHooks0[0]
	groupMixinInters0 := groupMixin[0].Interceptors()
	group.Interceptors[0] = groupMixinInters0[0]
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields0[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields0[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescSettings is the schema descriptor for settings field.
	groupDescSettings := groupFields[4].Descriptor()
	// group.DefaultSettings holds the default value on creation for the settings field.
	group.DefaultSettings = groupDescSettings.Default.(*types.GroupSetting)
	metadataMixin := schema.Metadata{}.Mixin()
	metadataMixinHooks0 := metadataMixin[0].Hooks()
	metadata.Hooks[0] = metadataMixinHooks0[0]
	metadataMixinInters0 := metadataMixin[0].Interceptors()
	metadata.Interceptors[0] = metadataMixinInters0[0]
	metadataMixinFields0 := metadataMixin[0].Fields()
	_ = metadataMixinFields0
	metadataFields := schema.Metadata{}.Fields()
	_ = metadataFields
	// metadataDescCreatedAt is the schema descriptor for created_at field.
	metadataDescCreatedAt := metadataMixinFields0[0].Descriptor()
	// metadata.DefaultCreatedAt holds the default value on creation for the created_at field.
	metadata.DefaultCreatedAt = metadataDescCreatedAt.Default.(func() time.Time)
	// metadataDescUpdatedAt is the schema descriptor for updated_at field.
	metadataDescUpdatedAt := metadataMixinFields0[1].Descriptor()
	// metadata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metadata.DefaultUpdatedAt = metadataDescUpdatedAt.Default.(func() time.Time)
	// metadata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metadata.UpdateDefaultUpdatedAt = metadataDescUpdatedAt.UpdateDefault.(func() time.Time)
	// metadataDescIsPublic is the schema descriptor for is_public field.
	metadataDescIsPublic := metadataFields[3].Descriptor()
	// metadata.DefaultIsPublic holds the default value on creation for the is_public field.
	metadata.DefaultIsPublic = metadataDescIsPublic.Default.(bool)
	nodeMixin := schema.Node{}.Mixin()
	nodeMixinHooks0 := nodeMixin[0].Hooks()
	node.Hooks[0] = nodeMixinHooks0[0]
	nodeMixinInters0 := nodeMixin[0].Interceptors()
	node.Interceptors[0] = nodeMixinInters0[0]
	nodeMixinFields0 := nodeMixin[0].Fields()
	_ = nodeMixinFields0
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeMixinFields0[0].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeMixinFields0[1].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() time.Time)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// nodeDescSettings is the schema descriptor for settings field.
	nodeDescSettings := nodeFields[6].Descriptor()
	// node.DefaultSettings holds the default value on creation for the settings field.
	node.DefaultSettings = nodeDescSettings.Default.(*types.NodeSetting)
	// nodeDescWeight is the schema descriptor for weight field.
	nodeDescWeight := nodeFields[7].Descriptor()
	// node.DefaultWeight holds the default value on creation for the weight field.
	node.DefaultWeight = nodeDescWeight.Default.(int)
	oauthclientMixin := schema.OAuthClient{}.Mixin()
	oauthclientMixinHooks0 := oauthclientMixin[0].Hooks()
	oauthclient.Hooks[0] = oauthclientMixinHooks0[0]
	oauthclientMixinInters0 := oauthclientMixin[0].Interceptors()
	oauthclient.Interceptors[0] = oauthclientMixinInters0[0]
	oauthclientMixinFields0 := oauthclientMixin[0].Fields()
	_ = oauthclientMixinFields0
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientMixinFields0[0].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
	// oauthclientDescUpdatedAt is the schema descriptor for updated_at field.
	oauthclientDescUpdatedAt := oauthclientMixinFields0[1].Descriptor()
	// oauthclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthclient.DefaultUpdatedAt = oauthclientDescUpdatedAt.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthclient.UpdateDefaultUpdatedAt = oauthclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthclientDescGUID is the schema descriptor for guid field.
	oauthclientDescGUID := oauthclientFields[0].Descriptor()
	// oauthclient.GUIDValidator is a validator for the "guid" field. It is called by the builders before save.
	oauthclient.GUIDValidator = oauthclientDescGUID.Validators[0].(func(string) error)
	// oauthclientDescSecret is the schema descriptor for secret field.
	oauthclientDescSecret := oauthclientFields[1].Descriptor()
	// oauthclient.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	oauthclient.SecretValidator = oauthclientDescSecret.Validators[0].(func(string) error)
	// oauthclientDescName is the schema descriptor for name field.
	oauthclientDescName := oauthclientFields[2].Descriptor()
	// oauthclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauthclient.NameValidator = oauthclientDescName.Validators[0].(func(string) error)
	// oauthclientDescHomepageURL is the schema descriptor for homepage_url field.
	oauthclientDescHomepageURL := oauthclientFields[3].Descriptor()
	// oauthclient.HomepageURLValidator is a validator for the "homepage_url" field. It is called by the builders before save.
	oauthclient.HomepageURLValidator = oauthclientDescHomepageURL.Validators[0].(func(string) error)
	// oauthclientDescRedirectUris is the schema descriptor for redirect_uris field.
	oauthclientDescRedirectUris := oauthclientFields[4].Descriptor()
	// oauthclient.DefaultRedirectUris holds the default value on creation for the redirect_uris field.
	oauthclient.DefaultRedirectUris = oauthclientDescRedirectUris.Default.([]string)
	// oauthclientDescScopes is the schema descriptor for scopes field.
	oauthclientDescScopes := oauthclientFields[5].Descriptor()
	// oauthclient.DefaultScopes holds the default value on creation for the scopes field.
	oauthclient.DefaultScopes = oauthclientDescScopes.Default.([]string)
	// oauthclientDescProps is the schema descriptor for props field.
	oauthclientDescProps := oauthclientFields[6].Descriptor()
	// oauthclient.DefaultProps holds the default value on creation for the props field.
	oauthclient.DefaultProps = oauthclientDescProps.Default.(*types.OAuthClientProps)
	// oauthclientDescIsEnabled is the schema descriptor for is_enabled field.
	oauthclientDescIsEnabled := oauthclientFields[7].Descriptor()
	// oauthclient.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	oauthclient.DefaultIsEnabled = oauthclientDescIsEnabled.Default.(bool)
	oauthgrantMixin := schema.OAuthGrant{}.Mixin()
	oauthgrantMixinHooks0 := oauthgrantMixin[0].Hooks()
	oauthgrant.Hooks[0] = oauthgrantMixinHooks0[0]
	oauthgrantMixinInters0 := oauthgrantMixin[0].Interceptors()
	oauthgrant.Interceptors[0] = oauthgrantMixinInters0[0]
	oauthgrantMixinFields0 := oauthgrantMixin[0].Fields()
	_ = oauthgrantMixinFields0
	oauthgrantFields := schema.OAuthGrant{}.Fields()
	_ = oauthgrantFields
	// oauthgrantDescCreatedAt is the schema descriptor for created_at field.
	oauthgrantDescCreatedAt := oauthgrantMixinFields0[0].Descriptor()
	// oauthgrant.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthgrant.DefaultCreatedAt = oauthgrantDescCreatedAt.Default.(func() time.Time)
	// oauthgrantDescUpdatedAt is the schema descriptor for updated_at field.
	oauthgrantDescUpdatedAt := oauthgrantMixinFields0[1].Descriptor()
	// oauthgrant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthgrant.DefaultUpdatedAt = oauthgrantDescUpdatedAt.Default.(func() time.Time)
	// oauthgrant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthgrant.UpdateDefaultUpdatedAt = oauthgrantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthgrantDescScopes is the schema descriptor for scopes field.
	oauthgrantDescScopes := oauthgrantFields[2].Descriptor()
	// oauthgrant.DefaultScopes holds the default value on creation for the scopes field.
	oauthgrant.DefaultScopes = oauthgrantDescScopes.Default.([]string)
	passkeyMixin := schema.Passkey{}.Mixin()
	passkeyMixinHooks0 := passkeyMixin[0].Hooks()
	passkey.Hooks[0] = passkeyMixinHooks0[0]
	passkeyMixinInters0 := passkeyMixin[0].Interceptors()
	passkey.Interceptors[0] = passkeyMixinInters0[0]
	passkeyMixinFields0 := passkeyMixin[0].Fields()
	_ = passkeyMixinFields0
	passkeyFields := schema.Passkey{}.Fields()
	_ = passkeyFields
	// passkeyDescCreatedAt is the schema descriptor for created_at field.
	passkeyDescCreatedAt := passkeyMixinFields0[0].Descriptor()
	// passkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	passkey.DefaultCreatedAt = passkeyDescCreatedAt.Default.(func() time.Time)
	// passkeyDescUpdatedAt is the schema descriptor for updated_at field.
	passkeyDescUpdatedAt := passkeyMixinFields0[1].Descriptor()
	// passkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	passkey.DefaultUpdatedAt = passkeyDescUpdatedAt.Default.(func() time.Time)
	// passkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	passkey.UpdateDefaultUpdatedAt = passkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinHooks0 := settingMixin[0].Hooks()
	setting.Hooks[0] = settingMixinHooks0[0]
	settingMixinInters0 := settingMixin[0].Interceptors()
	setting.Interceptors[0] = settingMixinInters0[0]
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	shareMixin := schema.Share{}.Mixin()
	shareMixinHooks0 := shareMixin[0].Hooks()
	share.Hooks[0] = shareMixinHooks0[0]
	shareMixinInters0 := shareMixin[0].Interceptors()
	share.Interceptors[0] = shareMixinInters0[0]
	shareMixinFields0 := shareMixin[0].Fields()
	_ = shareMixinFields0
	shareFields := schema.Share{}.Fields()
	_ = shareFields
	// shareDescCreatedAt is the schema descriptor for created_at field.
	shareDescCreatedAt := shareMixinFields0[0].Descriptor()
	// share.DefaultCreatedAt holds the default value on creation for the created_at field.
	share.DefaultCreatedAt = shareDescCreatedAt.Default.(func() time.Time)
	// shareDescUpdatedAt is the schema descriptor for updated_at field.
	shareDescUpdatedAt := shareMixinFields0[1].Descriptor()
	// share.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	share.DefaultUpdatedAt = shareDescUpdatedAt.Default.(func() time.Time)
	// share.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	share.UpdateDefaultUpdatedAt = shareDescUpdatedAt.UpdateDefault.(func() time.Time)
	// shareDescViews is the schema descriptor for views field.
	shareDescViews := shareFields[1].Descriptor()
	// share.DefaultViews holds the default value on creation for the views field.
	share.DefaultViews = shareDescViews.Default.(int)
	// shareDescDownloads is the schema descriptor for downloads field.
	shareDescDownloads := shareFields[2].Descriptor()
	// share.DefaultDownloads holds the default value on creation for the downloads field.
	share.DefaultDownloads = shareDescDownloads.Default.(int)
	storagepolicyMixin := schema.StoragePolicy{}.Mixin()
	storagepolicyMixinHooks0 := storagepolicyMixin[0].Hooks()
	storagepolicy.Hooks[0] = storagepolicyMixinHooks0[0]
	storagepolicyMixinInters0 := storagepolicyMixin[0].Interceptors()
	storagepolicy.Interceptors[0] = storagepolicyMixinInters0[0]
	storagepolicyMixinFields0 := storagepolicyMixin[0].Fields()
	_ = storagepolicyMixinFields0
	storagepolicyFields := schema.StoragePolicy{}.Fields()
	_ = storagepolicyFields
	// storagepolicyDescCreatedAt is the schema descriptor for created_at field.
	storagepolicyDescCreatedAt := storagepolicyMixinFields0[0].Descriptor()
	// storagepolicy.DefaultCreatedAt holds the default value on creation for the created_at field.
	storagepolicy.DefaultCreatedAt = storagepolicyDescCreatedAt.Default.(func() time.Time)
	// storagepolicyDescUpdatedAt is the schema descriptor for updated_at field.
	storagepolicyDescUpdatedAt := storagepolicyMixinFields0[1].Descriptor()
	// storagepolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storagepolicy.DefaultUpdatedAt = storagepolicyDescUpdatedAt.Default.(func() time.Time)
	// storagepolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storagepolicy.UpdateDefaultUpdatedAt = storagepolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// storagepolicyDescSettings is the schema descriptor for settings field.
	storagepolicyDescSettings := storagepolicyFields[10].Descriptor()
	// storagepolicy.DefaultSettings holds the default value on creation for the settings field.
	storagepolicy.DefaultSettings = storagepolicyDescSettings.Default.(*types.PolicySetting)
	taskMixin := schema.Task{}.Mixin()
	taskMixinHooks0 := taskMixin[0].Hooks()
	task.Hooks[0] = taskMixinHooks0[0]
	taskMixinInters0 := taskMixin[0].Interceptors()
	task.Interceptors[0] = taskMixinInters0[0]
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	teamactivityMixin := schema.TeamActivity{}.Mixin()
	teamactivityMixinHooks0 := teamactivityMixin[0].Hooks()
	teamactivity.Hooks[0] = teamactivityMixinHooks0[0]
	teamactivityMixinInters0 := teamactivityMixin[0].Interceptors()
	teamactivity.Interceptors[0] = teamactivityMixinInters0[0]
	teamactivityMixinFields0 := teamactivityMixin[0].Fields()
	_ = teamactivityMixinFields0
	teamactivityFields := schema.TeamActivity{}.Fields()
	_ = teamactivityFields
	// teamactivityDescCreatedAt is the schema descriptor for created_at field.
	teamactivityDescCreatedAt := teamactivityMixinFields0[0].Descriptor()
	// teamactivity.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamactivity.DefaultCreatedAt = teamactivityDescCreatedAt.Default.(func() time.Time)
	// teamactivityDescUpdatedAt is the schema descriptor for updated_at field.
	teamactivityDescUpdatedAt := teamactivityMixinFields0[1].Descriptor()
	// teamactivity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamactivity.DefaultUpdatedAt = teamactivityDescUpdatedAt.Default.(func() time.Time)
	// teamactivity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamactivity.UpdateDefaultUpdatedAt = teamactivityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamactivityDescAction is the schema descriptor for action field.
	teamactivityDescAction := teamactivityFields[3].Descriptor()
	// teamactivity.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	teamactivity.ActionValidator = teamactivityDescAction.Validators[0].(func(string) error)
	teamdocMixin := schema.TeamDoc{}.Mixin()
	teamdocMixinHooks0 := teamdocMixin[0].Hooks()
	teamdoc.Hooks[0] = teamdocMixinHooks0[0]
	teamdocMixinInters0 := teamdocMixin[0].Interceptors()
	teamdoc.Interceptors[0] = teamdocMixinInters0[0]
	teamdocMixinFields0 := teamdocMixin[0].Fields()
	_ = teamdocMixinFields0
	teamdocFields := schema.TeamDoc{}.Fields()
	_ = teamdocFields
	// teamdocDescCreatedAt is the schema descriptor for created_at field.
	teamdocDescCreatedAt := teamdocMixinFields0[0].Descriptor()
	// teamdoc.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamdoc.DefaultCreatedAt = teamdocDescCreatedAt.Default.(func() time.Time)
	// teamdocDescUpdatedAt is the schema descriptor for updated_at field.
	teamdocDescUpdatedAt := teamdocMixinFields0[1].Descriptor()
	// teamdoc.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamdoc.DefaultUpdatedAt = teamdocDescUpdatedAt.Default.(func() time.Time)
	// teamdoc.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamdoc.UpdateDefaultUpdatedAt = teamdocDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamdocDescTitle is the schema descriptor for title field.
	teamdocDescTitle := teamdocFields[2].Descriptor()
	// teamdoc.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	teamdoc.TitleValidator = teamdocDescTitle.Validators[0].(func(string) error)
	// teamdocDescContent is the schema descriptor for content field.
	teamdocDescContent := teamdocFields[3].Descriptor()
	// teamdoc.DefaultContent holds the default value on creation for the content field.
	teamdoc.DefaultContent = teamdocDescContent.Default.(string)
	// teamdocDescSortOrder is the schema descriptor for sort_order field.
	teamdocDescSortOrder := teamdocFields[6].Descriptor()
	// teamdoc.DefaultSortOrder holds the default value on creation for the sort_order field.
	teamdoc.DefaultSortOrder = teamdocDescSortOrder.Default.(float64)
	// teamdocDescIsFolder is the schema descriptor for is_folder field.
	teamdocDescIsFolder := teamdocFields[7].Descriptor()
	// teamdoc.DefaultIsFolder holds the default value on creation for the is_folder field.
	teamdoc.DefaultIsFolder = teamdocDescIsFolder.Default.(bool)
	// teamdocDescIcon is the schema descriptor for icon field.
	teamdocDescIcon := teamdocFields[8].Descriptor()
	// teamdoc.DefaultIcon holds the default value on creation for the icon field.
	teamdoc.DefaultIcon = teamdocDescIcon.Default.(string)
	teammemberMixin := schema.TeamMember{}.Mixin()
	teammemberMixinHooks0 := teammemberMixin[0].Hooks()
	teammember.Hooks[0] = teammemberMixinHooks0[0]
	teammemberMixinInters0 := teammemberMixin[0].Interceptors()
	teammember.Interceptors[0] = teammemberMixinInters0[0]
	teammemberMixinFields0 := teammemberMixin[0].Fields()
	_ = teammemberMixinFields0
	teammemberFields := schema.TeamMember{}.Fields()
	_ = teammemberFields
	// teammemberDescCreatedAt is the schema descriptor for created_at field.
	teammemberDescCreatedAt := teammemberMixinFields0[0].Descriptor()
	// teammember.DefaultCreatedAt holds the default value on creation for the created_at field.
	teammember.DefaultCreatedAt = teammemberDescCreatedAt.Default.(func() time.Time)
	// teammemberDescUpdatedAt is the schema descriptor for updated_at field.
	teammemberDescUpdatedAt := teammemberMixinFields0[1].Descriptor()
	// teammember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teammember.DefaultUpdatedAt = teammemberDescUpdatedAt.Default.(func() time.Time)
	// teammember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teammember.UpdateDefaultUpdatedAt = teammemberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teammemberDescRole is the schema descriptor for role field.
	teammemberDescRole := teammemberFields[2].Descriptor()
	// teammember.DefaultRole holds the default value on creation for the role field.
	teammember.DefaultRole = teammemberDescRole.Default.(string)
	teamnotificationMixin := schema.TeamNotification{}.Mixin()
	teamnotificationMixinHooks0 := teamnotificationMixin[0].Hooks()
	teamnotification.Hooks[0] = teamnotificationMixinHooks0[0]
	teamnotificationMixinInters0 := teamnotificationMixin[0].Interceptors()
	teamnotification.Interceptors[0] = teamnotificationMixinInters0[0]
	teamnotificationMixinFields0 := teamnotificationMixin[0].Fields()
	_ = teamnotificationMixinFields0
	teamnotificationFields := schema.TeamNotification{}.Fields()
	_ = teamnotificationFields
	// teamnotificationDescCreatedAt is the schema descriptor for created_at field.
	teamnotificationDescCreatedAt := teamnotificationMixinFields0[0].Descriptor()
	// teamnotification.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamnotification.DefaultCreatedAt = teamnotificationDescCreatedAt.Default.(func() time.Time)
	// teamnotificationDescUpdatedAt is the schema descriptor for updated_at field.
	teamnotificationDescUpdatedAt := teamnotificationMixinFields0[1].Descriptor()
	// teamnotification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamnotification.DefaultUpdatedAt = teamnotificationDescUpdatedAt.Default.(func() time.Time)
	// teamnotification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamnotification.UpdateDefaultUpdatedAt = teamnotificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamnotificationDescActorID is the schema descriptor for actor_id field.
	teamnotificationDescActorID := teamnotificationFields[1].Descriptor()
	// teamnotification.DefaultActorID holds the default value on creation for the actor_id field.
	teamnotification.DefaultActorID = teamnotificationDescActorID.Default.(int)
	// teamnotificationDescType is the schema descriptor for type field.
	teamnotificationDescType := teamnotificationFields[2].Descriptor()
	// teamnotification.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	teamnotification.TypeValidator = teamnotificationDescType.Validators[0].(func(string) error)
	// teamnotificationDescTitle is the schema descriptor for title field.
	teamnotificationDescTitle := teamnotificationFields[7].Descriptor()
	// teamnotification.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	teamnotification.TitleValidator = teamnotificationDescTitle.Validators[0].(func(string) error)
	// teamnotificationDescBody is the schema descriptor for body field.
	teamnotificationDescBody := teamnotificationFields[8].Descriptor()
	// teamnotification.DefaultBody holds the default value on creation for the body field.
	teamnotification.DefaultBody = teamnotificationDescBody.Default.(string)
	// teamnotificationDescIsRead is the schema descriptor for is_read field.
	teamnotificationDescIsRead := teamnotificationFields[9].Descriptor()
	// teamnotification.DefaultIsRead holds the default value on creation for the is_read field.
	teamnotification.DefaultIsRead = teamnotificationDescIsRead.Default.(bool)
	teampostMixin := schema.TeamPost{}.Mixin()
	teampostMixinHooks0 := teampostMixin[0].Hooks()
	teampost.Hooks[0] = teampostMixinHooks0[0]
	teampostMixinInters0 := teampostMixin[0].Interceptors()
	teampost.Interceptors[0] = teampostMixinInters0[0]
	teampostMixinFields0 := teampostMixin[0].Fields()
	_ = teampostMixinFields0
	teampostFields := schema.TeamPost{}.Fields()
	_ = teampostFields
	// teampostDescCreatedAt is the schema descriptor for created_at field.
	teampostDescCreatedAt := teampostMixinFields0[0].Descriptor()
	// teampost.DefaultCreatedAt holds the default value on creation for the created_at field.
	teampost.DefaultCreatedAt = teampostDescCreatedAt.Default.(func() time.Time)
	// teampostDescUpdatedAt is the schema descriptor for updated_at field.
	teampostDescUpdatedAt := teampostMixinFields0[1].Descriptor()
	// teampost.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teampost.DefaultUpdatedAt = teampostDescUpdatedAt.Default.(func() time.Time)
	// teampost.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teampost.UpdateDefaultUpdatedAt = teampostDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teampostDescFloor is the schema descriptor for floor field.
	teampostDescFloor := teampostFields[3].Descriptor()
	// teampost.DefaultFloor holds the default value on creation for the floor field.
	teampost.DefaultFloor = teampostDescFloor.Default.(int)
	teamprojectMixin := schema.TeamProject{}.Mixin()
	teamprojectMixinHooks0 := teamprojectMixin[0].Hooks()
	teamproject.Hooks[0] = teamprojectMixinHooks0[0]
	teamprojectMixinInters0 := teamprojectMixin[0].Interceptors()
	teamproject.Interceptors[0] = teamprojectMixinInters0[0]
	teamprojectMixinFields0 := teamprojectMixin[0].Fields()
	_ = teamprojectMixinFields0
	teamprojectFields := schema.TeamProject{}.Fields()
	_ = teamprojectFields
	// teamprojectDescCreatedAt is the schema descriptor for created_at field.
	teamprojectDescCreatedAt := teamprojectMixinFields0[0].Descriptor()
	// teamproject.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamproject.DefaultCreatedAt = teamprojectDescCreatedAt.Default.(func() time.Time)
	// teamprojectDescUpdatedAt is the schema descriptor for updated_at field.
	teamprojectDescUpdatedAt := teamprojectMixinFields0[1].Descriptor()
	// teamproject.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamproject.DefaultUpdatedAt = teamprojectDescUpdatedAt.Default.(func() time.Time)
	// teamproject.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamproject.UpdateDefaultUpdatedAt = teamprojectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamprojectDescName is the schema descriptor for name field.
	teamprojectDescName := teamprojectFields[0].Descriptor()
	// teamproject.NameValidator is a validator for the "name" field. It is called by the builders before save.
	teamproject.NameValidator = teamprojectDescName.Validators[0].(func(string) error)
	// teamprojectDescDescription is the schema descriptor for description field.
	teamprojectDescDescription := teamprojectFields[1].Descriptor()
	// teamproject.DefaultDescription holds the default value on creation for the description field.
	teamproject.DefaultDescription = teamprojectDescDescription.Default.(string)
	// teamprojectDescStatus is the schema descriptor for status field.
	teamprojectDescStatus := teamprojectFields[3].Descriptor()
	// teamproject.DefaultStatus holds the default value on creation for the status field.
	teamproject.DefaultStatus = teamprojectDescStatus.Default.(string)
	teamtaskMixin := schema.TeamTask{}.Mixin()
	teamtaskMixinHooks0 := teamtaskMixin[0].Hooks()
	teamtask.Hooks[0] = teamtaskMixinHooks0[0]
	teamtaskMixinInters0 := teamtaskMixin[0].Interceptors()
	teamtask.Interceptors[0] = teamtaskMixinInters0[0]
	teamtaskMixinFields0 := teamtaskMixin[0].Fields()
	_ = teamtaskMixinFields0
	teamtaskFields := schema.TeamTask{}.Fields()
	_ = teamtaskFields
	// teamtaskDescCreatedAt is the schema descriptor for created_at field.
	teamtaskDescCreatedAt := teamtaskMixinFields0[0].Descriptor()
	// teamtask.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamtask.DefaultCreatedAt = teamtaskDescCreatedAt.Default.(func() time.Time)
	// teamtaskDescUpdatedAt is the schema descriptor for updated_at field.
	teamtaskDescUpdatedAt := teamtaskMixinFields0[1].Descriptor()
	// teamtask.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamtask.DefaultUpdatedAt = teamtaskDescUpdatedAt.Default.(func() time.Time)
	// teamtask.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamtask.UpdateDefaultUpdatedAt = teamtaskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamtaskDescTitle is the schema descriptor for title field.
	teamtaskDescTitle := teamtaskFields[2].Descriptor()
	// teamtask.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	teamtask.TitleValidator = teamtaskDescTitle.Validators[0].(func(string) error)
	// teamtaskDescDescription is the schema descriptor for description field.
	teamtaskDescDescription := teamtaskFields[3].Descriptor()
	// teamtask.DefaultDescription holds the default value on creation for the description field.
	teamtask.DefaultDescription = teamtaskDescDescription.Default.(string)
	// teamtaskDescStatus is the schema descriptor for status field.
	teamtaskDescStatus := teamtaskFields[4].Descriptor()
	// teamtask.DefaultStatus holds the default value on creation for the status field.
	teamtask.DefaultStatus = teamtaskDescStatus.Default.(string)
	// teamtaskDescPriority is the schema descriptor for priority field.
	teamtaskDescPriority := teamtaskFields[5].Descriptor()
	// teamtask.DefaultPriority holds the default value on creation for the priority field.
	teamtask.DefaultPriority = teamtaskDescPriority.Default.(string)
	// teamtaskDescSortOrder is the schema descriptor for sort_order field.
	teamtaskDescSortOrder := teamtaskFields[11].Descriptor()
	// teamtask.DefaultSortOrder holds the default value on creation for the sort_order field.
	teamtask.DefaultSortOrder = teamtaskDescSortOrder.Default.(float64)
	// teamtaskDescProgress is the schema descriptor for progress field.
	teamtaskDescProgress := teamtaskFields[13].Descriptor()
	// teamtask.DefaultProgress holds the default value on creation for the progress field.
	teamtask.DefaultProgress = teamtaskDescProgress.Default.(int)
	teamtaskattachmentMixin := schema.TeamTaskAttachment{}.Mixin()
	teamtaskattachmentMixinHooks0 := teamtaskattachmentMixin[0].Hooks()
	teamtaskattachment.Hooks[0] = teamtaskattachmentMixinHooks0[0]
	teamtaskattachmentMixinInters0 := teamtaskattachmentMixin[0].Interceptors()
	teamtaskattachment.Interceptors[0] = teamtaskattachmentMixinInters0[0]
	teamtaskattachmentMixinFields0 := teamtaskattachmentMixin[0].Fields()
	_ = teamtaskattachmentMixinFields0
	teamtaskattachmentFields := schema.TeamTaskAttachment{}.Fields()
	_ = teamtaskattachmentFields
	// teamtaskattachmentDescCreatedAt is the schema descriptor for created_at field.
	teamtaskattachmentDescCreatedAt := teamtaskattachmentMixinFields0[0].Descriptor()
	// teamtaskattachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamtaskattachment.DefaultCreatedAt = teamtaskattachmentDescCreatedAt.Default.(func() time.Time)
	// teamtaskattachmentDescUpdatedAt is the schema descriptor for updated_at field.
	teamtaskattachmentDescUpdatedAt := teamtaskattachmentMixinFields0[1].Descriptor()
	// teamtaskattachment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamtaskattachment.DefaultUpdatedAt = teamtaskattachmentDescUpdatedAt.Default.(func() time.Time)
	// teamtaskattachment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamtaskattachment.UpdateDefaultUpdatedAt = teamtaskattachmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamtaskattachmentDescName is the schema descriptor for name field.
	teamtaskattachmentDescName := teamtaskattachmentFields[3].Descriptor()
	// teamtaskattachment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	teamtaskattachment.NameValidator = teamtaskattachmentDescName.Validators[0].(func(string) error)
	// teamtaskattachmentDescSize is the schema descriptor for size field.
	teamtaskattachmentDescSize := teamtaskattachmentFields[4].Descriptor()
	// teamtaskattachment.DefaultSize holds the default value on creation for the size field.
	teamtaskattachment.DefaultSize = teamtaskattachmentDescSize.Default.(int64)
	teamtaskcollaboratorMixin := schema.TeamTaskCollaborator{}.Mixin()
	teamtaskcollaboratorMixinHooks0 := teamtaskcollaboratorMixin[0].Hooks()
	teamtaskcollaborator.Hooks[0] = teamtaskcollaboratorMixinHooks0[0]
	teamtaskcollaboratorMixinInters0 := teamtaskcollaboratorMixin[0].Interceptors()
	teamtaskcollaborator.Interceptors[0] = teamtaskcollaboratorMixinInters0[0]
	teamtaskcollaboratorMixinFields0 := teamtaskcollaboratorMixin[0].Fields()
	_ = teamtaskcollaboratorMixinFields0
	teamtaskcollaboratorFields := schema.TeamTaskCollaborator{}.Fields()
	_ = teamtaskcollaboratorFields
	// teamtaskcollaboratorDescCreatedAt is the schema descriptor for created_at field.
	teamtaskcollaboratorDescCreatedAt := teamtaskcollaboratorMixinFields0[0].Descriptor()
	// teamtaskcollaborator.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamtaskcollaborator.DefaultCreatedAt = teamtaskcollaboratorDescCreatedAt.Default.(func() time.Time)
	// teamtaskcollaboratorDescUpdatedAt is the schema descriptor for updated_at field.
	teamtaskcollaboratorDescUpdatedAt := teamtaskcollaboratorMixinFields0[1].Descriptor()
	// teamtaskcollaborator.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamtaskcollaborator.DefaultUpdatedAt = teamtaskcollaboratorDescUpdatedAt.Default.(func() time.Time)
	// teamtaskcollaborator.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamtaskcollaborator.UpdateDefaultUpdatedAt = teamtaskcollaboratorDescUpdatedAt.UpdateDefault.(func() time.Time)
	teamtaskcommentMixin := schema.TeamTaskComment{}.Mixin()
	teamtaskcommentMixinHooks0 := teamtaskcommentMixin[0].Hooks()
	teamtaskcomment.Hooks[0] = teamtaskcommentMixinHooks0[0]
	teamtaskcommentMixinInters0 := teamtaskcommentMixin[0].Interceptors()
	teamtaskcomment.Interceptors[0] = teamtaskcommentMixinInters0[0]
	teamtaskcommentMixinFields0 := teamtaskcommentMixin[0].Fields()
	_ = teamtaskcommentMixinFields0
	teamtaskcommentFields := schema.TeamTaskComment{}.Fields()
	_ = teamtaskcommentFields
	// teamtaskcommentDescCreatedAt is the schema descriptor for created_at field.
	teamtaskcommentDescCreatedAt := teamtaskcommentMixinFields0[0].Descriptor()
	// teamtaskcomment.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamtaskcomment.DefaultCreatedAt = teamtaskcommentDescCreatedAt.Default.(func() time.Time)
	// teamtaskcommentDescUpdatedAt is the schema descriptor for updated_at field.
	teamtaskcommentDescUpdatedAt := teamtaskcommentMixinFields0[1].Descriptor()
	// teamtaskcomment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamtaskcomment.DefaultUpdatedAt = teamtaskcommentDescUpdatedAt.Default.(func() time.Time)
	// teamtaskcomment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamtaskcomment.UpdateDefaultUpdatedAt = teamtaskcommentDescUpdatedAt.UpdateDefault.(func() time.Time)
	teamtopicMixin := schema.TeamTopic{}.Mixin()
	teamtopicMixinHooks0 := teamtopicMixin[0].Hooks()
	teamtopic.Hooks[0] = teamtopicMixinHooks0[0]
	teamtopicMixinInters0 := teamtopicMixin[0].Interceptors()
	teamtopic.Interceptors[0] = teamtopicMixinInters0[0]
	teamtopicMixinFields0 := teamtopicMixin[0].Fields()
	_ = teamtopicMixinFields0
	teamtopicFields := schema.TeamTopic{}.Fields()
	_ = teamtopicFields
	// teamtopicDescCreatedAt is the schema descriptor for created_at field.
	teamtopicDescCreatedAt := teamtopicMixinFields0[0].Descriptor()
	// teamtopic.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamtopic.DefaultCreatedAt = teamtopicDescCreatedAt.Default.(func() time.Time)
	// teamtopicDescUpdatedAt is the schema descriptor for updated_at field.
	teamtopicDescUpdatedAt := teamtopicMixinFields0[1].Descriptor()
	// teamtopic.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamtopic.DefaultUpdatedAt = teamtopicDescUpdatedAt.Default.(func() time.Time)
	// teamtopic.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamtopic.UpdateDefaultUpdatedAt = teamtopicDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamtopicDescTitle is the schema descriptor for title field.
	teamtopicDescTitle := teamtopicFields[1].Descriptor()
	// teamtopic.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	teamtopic.TitleValidator = teamtopicDescTitle.Validators[0].(func(string) error)
	// teamtopicDescContent is the schema descriptor for content field.
	teamtopicDescContent := teamtopicFields[2].Descriptor()
	// teamtopic.DefaultContent holds the default value on creation for the content field.
	teamtopic.DefaultContent = teamtopicDescContent.Default.(string)
	// teamtopicDescCategory is the schema descriptor for category field.
	teamtopicDescCategory := teamtopicFields[3].Descriptor()
	// teamtopic.DefaultCategory holds the default value on creation for the category field.
	teamtopic.DefaultCategory = teamtopicDescCategory.Default.(string)
	// teamtopicDescIsPinned is the schema descriptor for is_pinned field.
	teamtopicDescIsPinned := teamtopicFields[5].Descriptor()
	// teamtopic.DefaultIsPinned holds the default value on creation for the is_pinned field.
	teamtopic.DefaultIsPinned = teamtopicDescIsPinned.Default.(bool)
	// teamtopicDescIsLocked is the schema descriptor for is_locked field.
	teamtopicDescIsLocked := teamtopicFields[6].Descriptor()
	// teamtopic.DefaultIsLocked holds the default value on creation for the is_locked field.
	teamtopic.DefaultIsLocked = teamtopicDescIsLocked.Default.(bool)
	// teamtopicDescIsResolved is the schema descriptor for is_resolved field.
	teamtopicDescIsResolved := teamtopicFields[7].Descriptor()
	// teamtopic.DefaultIsResolved holds the default value on creation for the is_resolved field.
	teamtopic.DefaultIsResolved = teamtopicDescIsResolved.Default.(bool)
	// teamtopicDescReplyTotal is the schema descriptor for reply_total field.
	teamtopicDescReplyTotal := teamtopicFields[8].Descriptor()
	// teamtopic.DefaultReplyTotal holds the default value on creation for the reply_total field.
	teamtopic.DefaultReplyTotal = teamtopicDescReplyTotal.Default.(int)
	// teamtopicDescViewTotal is the schema descriptor for view_total field.
	teamtopicDescViewTotal := teamtopicFields[9].Descriptor()
	// teamtopic.DefaultViewTotal holds the default value on creation for the view_total field.
	teamtopic.DefaultViewTotal = teamtopicDescViewTotal.Default.(int)
	// teamtopicDescLastReplyUserID is the schema descriptor for last_reply_user_id field.
	teamtopicDescLastReplyUserID := teamtopicFields[11].Descriptor()
	// teamtopic.DefaultLastReplyUserID holds the default value on creation for the last_reply_user_id field.
	teamtopic.DefaultLastReplyUserID = teamtopicDescLastReplyUserID.Default.(int)
	teamtopicattachmentMixin := schema.TeamTopicAttachment{}.Mixin()
	teamtopicattachmentMixinHooks0 := teamtopicattachmentMixin[0].Hooks()
	teamtopicattachment.Hooks[0] = teamtopicattachmentMixinHooks0[0]
	teamtopicattachmentMixinInters0 := teamtopicattachmentMixin[0].Interceptors()
	teamtopicattachment.Interceptors[0] = teamtopicattachmentMixinInters0[0]
	teamtopicattachmentMixinFields0 := teamtopicattachmentMixin[0].Fields()
	_ = teamtopicattachmentMixinFields0
	teamtopicattachmentFields := schema.TeamTopicAttachment{}.Fields()
	_ = teamtopicattachmentFields
	// teamtopicattachmentDescCreatedAt is the schema descriptor for created_at field.
	teamtopicattachmentDescCreatedAt := teamtopicattachmentMixinFields0[0].Descriptor()
	// teamtopicattachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	teamtopicattachment.DefaultCreatedAt = teamtopicattachmentDescCreatedAt.Default.(func() time.Time)
	// teamtopicattachmentDescUpdatedAt is the schema descriptor for updated_at field.
	teamtopicattachmentDescUpdatedAt := teamtopicattachmentMixinFields0[1].Descriptor()
	// teamtopicattachment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	teamtopicattachment.DefaultUpdatedAt = teamtopicattachmentDescUpdatedAt.Default.(func() time.Time)
	// teamtopicattachment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	teamtopicattachment.UpdateDefaultUpdatedAt = teamtopicattachmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// teamtopicattachmentDescName is the schema descriptor for name field.
	teamtopicattachmentDescName := teamtopicattachmentFields[3].Descriptor()
	// teamtopicattachment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	teamtopicattachment.NameValidator = teamtopicattachmentDescName.Validators[0].(func(string) error)
	// teamtopicattachmentDescSize is the schema descriptor for size field.
	teamtopicattachmentDescSize := teamtopicattachmentFields[4].Descriptor()
	// teamtopicattachment.DefaultSize holds the default value on creation for the size field.
	teamtopicattachment.DefaultSize = teamtopicattachmentDescSize.Default.(int64)
	userMixin := schema.User{}.Mixin()
	userMixinHooks0 := userMixin[0].Hooks()
	user.Hooks[0] = userMixinHooks0[0]
	userMixinInters0 := userMixin[0].Interceptors()
	user.Interceptors[0] = userMixinInters0[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescNick is the schema descriptor for nick field.
	userDescNick := userFields[1].Descriptor()
	// user.NickValidator is a validator for the "nick" field. It is called by the builders before save.
	user.NickValidator = userDescNick.Validators[0].(func(string) error)
	// userDescStorage is the schema descriptor for storage field.
	userDescStorage := userFields[4].Descriptor()
	// user.DefaultStorage holds the default value on creation for the storage field.
	user.DefaultStorage = userDescStorage.Default.(int64)
	// userDescSettings is the schema descriptor for settings field.
	userDescSettings := userFields[7].Descriptor()
	// user.DefaultSettings holds the default value on creation for the settings field.
	user.DefaultSettings = userDescSettings.Default.(*types.UserSetting)
}

const (
	Version = "v0.13.0"                                         // Version of ent codegen.
	Sum     = "h1:DclxWczaCpyiKn6ZWVcJjq1zIKtJ11iNKy+08lNYsJE=" // Sum of ent codegen.
)
