// Code generated by ent, DO NOT EDIT.

package teamnotification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldUserID, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldActorID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldType, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldProjectID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldTaskID, v))
}

// DocID applies equality check predicate on the "doc_id" field. It's identical to DocIDEQ.
func DocID(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldDocID, v))
}

// TopicID applies equality check predicate on the "topic_id" field. It's identical to TopicIDEQ.
func TopicID(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldTopicID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldTitle, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldBody, v))
}

// IsRead applies equality check predicate on the "is_read" field. It's identical to IsReadEQ.
func IsRead(v bool) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldIsRead, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldUserID, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotNull(FieldActorID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldContainsFold(FieldType, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotNull(FieldProjectID))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotNull(FieldTaskID))
}

// DocIDEQ applies the EQ predicate on the "doc_id" field.
func DocIDEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldDocID, v))
}

// DocIDNEQ applies the NEQ predicate on the "doc_id" field.
func DocIDNEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldDocID, v))
}

// DocIDIn applies the In predicate on the "doc_id" field.
func DocIDIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldDocID, vs...))
}

// DocIDNotIn applies the NotIn predicate on the "doc_id" field.
func DocIDNotIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldDocID, vs...))
}

// DocIDGT applies the GT predicate on the "doc_id" field.
func DocIDGT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldDocID, v))
}

// DocIDGTE applies the GTE predicate on the "doc_id" field.
func DocIDGTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldDocID, v))
}

// DocIDLT applies the LT predicate on the "doc_id" field.
func DocIDLT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldDocID, v))
}

// DocIDLTE applies the LTE predicate on the "doc_id" field.
func DocIDLTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldDocID, v))
}

// DocIDIsNil applies the IsNil predicate on the "doc_id" field.
func DocIDIsNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIsNull(FieldDocID))
}

// DocIDNotNil applies the NotNil predicate on the "doc_id" field.
func DocIDNotNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotNull(FieldDocID))
}

// TopicIDEQ applies the EQ predicate on the "topic_id" field.
func TopicIDEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldTopicID, v))
}

// TopicIDNEQ applies the NEQ predicate on the "topic_id" field.
func TopicIDNEQ(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldTopicID, v))
}

// TopicIDIn applies the In predicate on the "topic_id" field.
func TopicIDIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldTopicID, vs...))
}

// TopicIDNotIn applies the NotIn predicate on the "topic_id" field.
func TopicIDNotIn(vs ...int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldTopicID, vs...))
}

// TopicIDGT applies the GT predicate on the "topic_id" field.
func TopicIDGT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldTopicID, v))
}

// TopicIDGTE applies the GTE predicate on the "topic_id" field.
func TopicIDGTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldTopicID, v))
}

// TopicIDLT applies the LT predicate on the "topic_id" field.
func TopicIDLT(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldTopicID, v))
}

// TopicIDLTE applies the LTE predicate on the "topic_id" field.
func TopicIDLTE(v int) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldTopicID, v))
}

// TopicIDIsNil applies the IsNil predicate on the "topic_id" field.
func TopicIDIsNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIsNull(FieldTopicID))
}

// TopicIDNotNil applies the NotNil predicate on the "topic_id" field.
func TopicIDNotNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotNull(FieldTopicID))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldContainsFold(FieldTitle, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldHasSuffix(FieldBody, v))
}

// BodyIsNil applies the IsNil predicate on the "body" field.
func BodyIsNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldIsNull(FieldBody))
}

// BodyNotNil applies the NotNil predicate on the "body" field.
func BodyNotNil() predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNotNull(FieldBody))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldContainsFold(FieldBody, v))
}

// IsReadEQ applies the EQ predicate on the "is_read" field.
func IsReadEQ(v bool) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldEQ(FieldIsRead, v))
}

// IsReadNEQ applies the NEQ predicate on the "is_read" field.
func IsReadNEQ(v bool) predicate.TeamNotification {
	return predicate.TeamNotification(sql.FieldNEQ(FieldIsRead, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamNotification) predicate.TeamNotification {
	return predicate.TeamNotification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamNotification) predicate.TeamNotification {
	return predicate.TeamNotification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamNotification) predicate.TeamNotification {
	return predicate.TeamNotification(sql.NotPredicates(p))
}
